

profileDefault(profile("BTServer"),decision("deny")).
profileRule(profile("BTServer"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/ptmx")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/dtracehelper")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/aes_0")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension-class("com.apple.app-sandbox.read-write")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension-class("com.apple.app-sandbox.read")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension-class("com.apple.sandbox.pty"),regex("^/dev/ttys[0-9]"/i)])).
profileRule(profile("BTServer"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension-class("com.apple.sandbox.pty"),regex("^/dev/ttys[0-9]+"/i)])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/zero")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/random")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/urandom")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/aes_0")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/ptmx")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/dtracehelper")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Media/com.apple.itunes.lock_sync")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/Managed Preferences/mobile/")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.PeoplePicker.plist")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.AOSNotification.public.notbackedup.plist")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.AppSupport.plist")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.MobileAsset.plist")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.BTServer.airplane.plist")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.BTServer.plist")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.MobileBluetooth.devices.plist")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.MobileBluetooth.ledevices.plist")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.MobileBluetooth.services.plist")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/.GlobalPreferences.plist")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.MobileBluetooth.debug.plist")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.assistant.support.plist")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.coreaudio.plist")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.coremedia.plist")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/wireless/Library/CallHistory")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/wireless/Library/CallHistory/call_history.db")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/wireless/Library/CallHistory/call_history.db-journal")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/Library/Application Support/BTServer")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/Library/Application Support/BTServer/pincode_defaults.db")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/Library/Application Support/BTServer/pincode_defaults.db-journal")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/wireless/Library/Logs/awd/")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Logs/BTServer"/i)])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/com.apple.networkd.plist")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/com.apple.NetworkStatistics.plist")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/tmp/")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/db/timezone/")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([subpath("/System/Library/")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([subpath("/usr/lib/")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([subpath("/usr/share/")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([subpath("/System/Library/Frameworks/")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([subpath("/System/Library/PrivateFrameworks/")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/null")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([vnode-type(tty),regex("^/dev/ttyp[0-9a-f]$"/i)])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([vnode-type(tty),regex("^/dev/ptyp[0-9a-f]$"/i)])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([regex("^/dev/ttys[0-9]"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([regex("^/dev/ttys[0-9]+"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Assets/"),extension("com.apple.assets.read")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([extension("com.apple.app-sandbox.read-write"),regex("^/private/var/mobile/Applications//"/i)])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([extension("com.apple.app-sandbox.read-write"),regex("^/private/var/mobile/Applications/[-0-9A-Z]+/"/i)])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Developer/"),debug-mode])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Developer/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Developer/"),require-not(require-entitlement("platform-application"))])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/tmp/"),debug-mode])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/tmp/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/XcodeBuiltProducts/"),debug-mode])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/XcodeBuiltProducts/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/dev/")),literal("/private/etc/services")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/dev/")),literal("/")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/dev/")),literal("/private/var/mobile/Library/Caches/com.apple.MobileGestalt.plist")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/dev/")),subpath("/private/var/mobile/Library/ConfigurationProfiles/PublicInfo/")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/dev/")),literal("/private/etc/hosts")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/dev/")),literal("/private/etc/group")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/dev/")),literal("/private/etc/passwd")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/dev/")),literal("/private/etc/protocols")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.mobilephone.speeddial.plist")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/AddressBook/")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-readSTAR"),filters([extension("com.apple.tcc.kTCCServiceAddressBook")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-read-data"),filters([literal("/private/var/preferences/SystemConfiguration/com.apple.radios.plist")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-read-data"),filters([literal("/private/var/preferences/SystemConfiguration/preferences.plist")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-read-data"),filters([literal("/usr/sbin")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-read-data"),filters([literal("/usr/sbin/BTServer")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-read-data"),filters([subpath("/System/")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-read-data"),filters([literal("/dev/btwake")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-read-metadata"),filters([literal("/private/var/run/syslog")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-read-metadata"),filters([literal("/private/var/mobile")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-read-metadata"),filters([literal("/private/var/mobile/Library/Preferences")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-read-metadata"),filters([literal("/Library/Preferences")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-read-metadata"),filters([literal("/usr/sbin/BTServer")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-read-metadata"),filters([literal("/usr/sbin")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-read-metadata"),filters([literal("/private/var/wireless/Library")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-read-metadata"),filters([literal("/private/var/wireless")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-read-metadata"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.carrier.plist")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-read-metadata"),filters([literal("/private/var")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-read-metadata"),filters([vnode-type(symlink)])).
profileRule(profile("BTServer"),decision("allow"),operation("file-read-metadata"),filters([vnode-type(directory)])).
profileRule(profile("BTServer"),decision("allow"),operation("file-read-metadata"),filters([literal("/private/var/mobile/Library/Caches/powerlog.launchd")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-read-metadata"),filters([vnode-type(regular-file),extension("com.apple.private.safe-move.receive")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-read-metadata"),filters([vnode-type(regular-file),extension("com.apple.private.safe-move.send")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/ptmx")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/dtracehelper")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Media/com.apple.itunes.lock_sync")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/wireless/Library/CallHistory/call_history.db-journal")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]BTServer[.]airplane[.]plist"/i)])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]BTServer[.]plist"/i)])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]MobileBluetooth[.]devices[.]plist"/i)])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]MobileBluetooth[.]ledevices[.]plist"/i)])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]MobileBluetooth[.]services[.]plist"/i)])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]PeoplePicker[.]plist"/i)])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/wireless/Library/CallHistory")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/wireless/Library/CallHistory/call_history.db")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/Library/Application Support/BTServer/pincode_defaults.db-journal")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/Library/Application Support/BTServer")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/Library/Application Support/BTServer/pincode_defaults.db")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Library/Logs/CrashReporter/hci")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Logs/BTServer"/i)])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/wireless/Library/Logs/awd/")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/aes_0")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(tty),regex("^/dev/ttyp[0-9a-f]$"/i)])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(tty),regex("^/dev/ptyp[0-9a-f]$"/i)])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/dev/ttys[0-9]"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/dev/ttys[0-9]+"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension("com.apple.app-sandbox.read-write"),regex("^/private/var/mobile/Applications//"/i)])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension("com.apple.app-sandbox.read-write"),regex("^/private/var/mobile/Applications/[-0-9A-Z]+/"/i)])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/"),debug-mode])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(literal("/dev/urandom")),require-not(literal("/dev/random")),literal("/dev/zero")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(literal("/dev/urandom")),require-not(literal("/dev/random")),literal("/dev/null")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Library/Preferences/com.apple.mobilephone.speeddial.plist")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Library/AddressBook/")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension("com.apple.tcc.kTCCServiceAddressBook")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(regular-file),extension("com.apple.private.safe-move.send")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/wireless/Library/CallHistory/call_history.db")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/Library/Application Support/BTServer/pincode_defaults.db")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(regular-file),extension("com.apple.private.safe-move.send")])).
profileRule(profile("BTServer"),decision("allow"),operation("file-write-unlink"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(regular-file),extension("com.apple.private.safe-move.receive")])).
profileRule(profile("BTServer"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOHIDResourceDeviceUserClient")])).
profileRule(profile("BTServer"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleMobileFileIntegrityUserClient")])).
profileRule(profile("BTServer"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleBasebandUserClient")])).
profileRule(profile("BTServer"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("RootDomainUserClient")])).
profileRule(profile("BTServer"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOUserEthernetResourceUserClient")])).
profileRule(profile("BTServer"),decision("allow"),operation("iokit-get-properties"),filters([])).
profileRule(profile("BTServer"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name("shm_notif.tacl.R")])).
profileRule(profile("BTServer"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name("shm_notif.tacl.W")])).
profileRule(profile("BTServer"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name("shm_notif.tsco.R")])).
profileRule(profile("BTServer"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name("shm_notif.tsco.W")])).
profileRule(profile("BTServer"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name("shm_pcm_audio_sco_read")])).
profileRule(profile("BTServer"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name("shm_pcm_audio_sco_write")])).
profileRule(profile("BTServer"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^..:..:..:..:..:..-tacl$"/i)])).
profileRule(profile("BTServer"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^/FSM-"/i),debug-mode])).
profileRule(profile("BTServer"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^OA-"/i),debug-mode])).
profileRule(profile("BTServer"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^stack-logs"/i),debug-mode])).
profileRule(profile("BTServer"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-c$"/i),debug-mode])).
profileRule(profile("BTServer"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-s$"/i),debug-mode])).
profileRule(profile("BTServer"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^/FSM-"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("BTServer"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^OA-"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("BTServer"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^stack-logs"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("BTServer"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-c$"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("BTServer"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-s$"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("BTServer"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^/FSM-"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("BTServer"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^OA-"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("BTServer"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^stack-logs"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("BTServer"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-c$"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("BTServer"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-s$"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("BTServer"),decision("allow"),operation("ipc-posix-shm-readSTAR"),filters([ipc-posix-name("apple.shm.notification_center")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-bootstrap"),filters([])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.xpcd")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.tccd")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.mobilegestalt.xpc")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.lsd")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.backboard.processassertionconnection")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.system.logger")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.system.notification_center")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.distributed_notifications@1v3")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.managedconfiguration.profiled.public")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.cmfsyncagent.embedded.auth")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.identityservicesd.idquery.embedded.auth")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.ABDatabaseDoctor")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.mobileassetd")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.BlueTool")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.springboard.services")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.ProgressReporting")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.springboard.processinvalidation")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.springboard.backgroundappservices")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.securityd")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.mediaserverd")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.lsd.xpc")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coremedia.asset")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.commcenter.xpc")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.backboard.systemservices")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.backboard.applicationstateconnection")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.awdd")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.WirelessCoexManager")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.helper")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SBUserNotification")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.PowerManagement.control")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.MobileInternetSharing")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.BTServer.map")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.BTServer.le")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.BTServer.avrcp")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.BTAudioHALPlugin.xpc")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.configd")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.NetworkInformation")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.PPPController")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.DNSConfiguration")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.SCNetworkReachability")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.commcenter.cupolicy.xpc")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.usymptomsd")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.symptomsd")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.networkd")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.nsnetworkd")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.cfnetwork.AuthBrokerAgent")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.cfnetwork.cfnetworkagent")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.hangtracerd")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.ReportCrash.SimulateCrash")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.aggregated")])).
profileRule(profile("BTServer"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.itunesstored.xpc"),require-entitlement("com.apple.itunesstored.private",[])])).
profileRule(profile("BTServer"),decision("allow"),operation("network-outbound"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/tmp/launchd-[0-9]+[.][^/]+/sock$"/i))])).
profileRule(profile("BTServer"),decision("allow"),operation("privSTAR"),filters([])).
profileRule(profile("BTServer"),decision("allow"),operation("priv-adjtime"),filters([])).
profileRule(profile("BTServer"),decision("allow"),operation("priv-netinetSTAR"),filters([])).
profileRule(profile("BTServer"),decision("allow"),operation("priv-netinet-reservedport"),filters([])).
profileRule(profile("BTServer"),decision("allow"),operation("process-infoSTAR"),filters([])).
profileRule(profile("BTServer"),decision("allow"),operation("process-info-listpids"),filters([])).
profileRule(profile("BTServer"),decision("allow"),operation("process-info-pidinfo"),filters([])).
profileRule(profile("BTServer"),decision("allow"),operation("process-info-pidfdinfo"),filters([])).
profileRule(profile("BTServer"),decision("allow"),operation("process-info-pidfileportinfo"),filters([])).
profileRule(profile("BTServer"),decision("allow"),operation("process-info-setcontrol"),filters([])).
profileRule(profile("BTServer"),decision("allow"),operation("process-info-dirtycontrol"),filters([])).
profileRule(profile("BTServer"),decision("allow"),operation("process-info-rusage"),filters([])).
profileRule(profile("BTServer"),decision("allow"),operation("pseudo-tty"),filters([])).
profileRule(profile("BTServer"),decision("allow"),operation("signal"),filters([target(self)])).
profileRule(profile("BTServer"),decision("allow"),operation("sysctl-read"),filters([])).
profileRule(profile("BTServer"),decision("allow"),operation("system-sched"),filters([require-entitlement("com.apple.private.kernel.override-cpumon",[])])).
profileRule(profile("BTServer"),decision("allow"),operation("system-socket"),filters([socket-domain(af_route)])).
profileRule(profile("BTServer"),decision("allow"),operation("system-socket"),filters([socket-domain(af_system),socket-protocol(2)])).
