

profileDefault(profile("com.apple.sandboxd"),decision("deny")).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/dtracehelper")])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("file-readSTAR"),filters([])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("file-read-data"),filters([])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("file-read-metadata"),filters([])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("file-read-xattr"),filters([])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/")])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/logs/CrashReporter/Sandbox-.+[.]plist"/i)])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/cores/"/i),require-not(file-mode("#o0000"))])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/zero")])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/dtracehelper")])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/null")])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleMobileFileIntegrityUserClient")])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("iokit-get-properties"),filters([])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name("apple.shm.notification_center")])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("mach-bootstrap"),filters([])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.system.logger")])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.system.notification_center")])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coresymbolicationd")])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.mobilegestalt.xpc")])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.system.DirectoryService.libinfo_v1")])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("networkSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/tmp/sandbox[.]"/i)])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("network-outbound"),filters([regex("^/private/tmp/[.]webdavUDS[.][^/]+$"/i)])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("network-outbound"),filters([literal("/private/var/run/asl_input")])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("network-outbound"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/tmp/launchd-[0-9]+[.][^/]+/sock$"/i))])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("privSTAR"),filters([])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("priv-adjtime"),filters([])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("priv-netinetSTAR"),filters([])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("priv-netinet-reservedport"),filters([])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("process-infoSTAR"),filters([])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("process-info-listpids"),filters([])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("process-info-pidinfo"),filters([])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("process-info-pidfdinfo"),filters([])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("process-info-pidfileportinfo"),filters([])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("process-info-setcontrol"),filters([])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("process-info-dirtycontrol"),filters([])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("process-info-rusage"),filters([])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("signal"),filters([target(self)])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("signal"),filters([target(self)])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("sysctl-read"),filters([])).
profileRule(profile("com.apple.sandboxd"),decision("allow"),operation("system-info"),filters([info-type("net.link.addr")])).
