

profileDefault(profile("com.apple.tccd"),decision("deny")).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension-class-regex("^com[.]apple[.]tcc[.]"/i)])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("file-readSTAR"),filters([])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("file-read-data"),filters([])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("file-read-metadata"),filters([])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("file-read-xattr"),filters([])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/com.apple.tccd/")])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Library/TCC/")])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleMobileFileIntegrityUserClient")])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("iokit-get-properties"),filters([])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name("apple.shm.notification_center")])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("mach-bootstrap"),filters([])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.backboard.systemservices")])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.librariand")])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.mobile.installd")])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.springboard.backgroundappservices")])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.springboard.services")])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.system.logger")])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.system.notification_center")])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SBUserNotification")])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("network-outbound"),filters([regex("^/private/tmp/[.]webdavUDS[.][^/]+$"/i)])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("network-outbound"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/tmp/launchd-[0-9]+[.][^/]+/sock$"/i))])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("privSTAR"),filters([])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("priv-adjtime"),filters([])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("priv-netinetSTAR"),filters([])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("priv-netinet-reservedport"),filters([])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("process-infoSTAR"),filters([])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("process-info-listpids"),filters([])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("process-info-pidinfo"),filters([])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("process-info-pidfdinfo"),filters([])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("process-info-pidfileportinfo"),filters([])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("process-info-setcontrol"),filters([])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("process-info-dirtycontrol"),filters([])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("process-info-rusage"),filters([])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("signal"),filters([])).
profileRule(profile("com.apple.tccd"),decision("allow"),operation("sysctl-read"),filters([])).
