

profileDefault(profile("gputoolsd"),decision("deny")).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/ptmx")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/dtracehelper")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/aes_0")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension-class("com.apple.app-sandbox.read-write")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension-class("com.apple.app-sandbox.read")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/dtracehelper")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/tmp/")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/db/timezone/")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/System/Library/")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/usr/lib/")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/usr/share/")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/Managed Preferences/mobile/")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/.GlobalPreferences.plist")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/System/Library/Frameworks/")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/System/Library/PrivateFrameworks/")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/null")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/dev/"))])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/zero")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/random")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/urandom")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/aes_0")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/ptmx")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Developer/"),debug-mode])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Developer/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Developer/"),require-not(require-entitlement("platform-application"))])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/tmp/"),debug-mode])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/tmp/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/XcodeBuiltProducts/"),debug-mode])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/XcodeBuiltProducts/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([vnode-type(tty),regex("^/dev/ttyp[0-9a-f]$"/i)])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([vnode-type(tty),regex("^/dev/ptyp[0-9a-f]$"/i)])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([regex("^/dev/ttys[0-9]"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-readSTAR"),filters([regex("^/dev/ttys[0-9]+"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-read-metadata"),filters([literal("/private/var/run/syslog")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-read-metadata"),filters([vnode-type(symlink)])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-read-metadata"),filters([vnode-type(directory)])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-read-metadata"),filters([literal("/private/var/mobile")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-read-metadata"),filters([literal("/private/var/mobile/Library/Preferences")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-read-metadata"),filters([literal("/private/var/mobile/Library/Caches/powerlog.launchd")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-read-metadata"),filters([vnode-type(regular-file),extension("com.apple.private.safe-move.receive")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-read-metadata"),filters([vnode-type(regular-file),extension("com.apple.private.safe-move.send")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/dtracehelper")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Library/GPUTools/")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/root/Library/Caches/com.apple.opengl/")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/aes_0")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/ptmx")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/"),debug-mode])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(literal("/dev/urandom")),require-not(literal("/dev/random")),literal("/dev/zero")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(literal("/dev/urandom")),require-not(literal("/dev/random")),literal("/dev/null")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(tty),regex("^/dev/ttyp[0-9a-f]$"/i)])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(tty),regex("^/dev/ptyp[0-9a-f]$"/i)])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/dev/ttys[0-9]"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/dev/ttys[0-9]+"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(regular-file),extension("com.apple.private.safe-move.send")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(regular-file),extension("com.apple.private.safe-move.send")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("file-write-unlink"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(regular-file),extension("com.apple.private.safe-move.receive")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelSharedUserClient2")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelContext")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelDevice")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelSharedUserClient")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelContext2")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelDevice2")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleMobileFileIntegrityUserClient")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("iokit-get-properties"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("ipc-posix-shm-readSTAR"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("ipc-posix-shm-read-data"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("ipc-posix-shm-read-metadata"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("ipc-posix-shm-writeSTAR"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("ipc-posix-shm-write-create"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("ipc-posix-shm-write-data"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("ipc-posix-shm-write-unlink"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-bootstrap"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.xpcd")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.tccd")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.mobilegestalt.xpc")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.lsd")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.backboard.processassertionconnection")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.system.logger")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.system.notification_center")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.distributed_notifications@1v3")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.managedconfiguration.profiled.public")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.cvmsServ")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.gpumemd.source")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.lockdown.host_watcher")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.springboard.services")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.springboard.icongeneration")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.springboard.backgroundappservices")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.securityd")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coresymbolicationd")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.backboard.systemservices")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.backboard.appwatchdog")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.backboard.applicationstateconnection")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.hangtracerd")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.ReportCrash.SimulateCrash")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.aggregated")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.itunesstored.xpc"),require-entitlement("com.apple.itunesstored.private",[])])).
profileRule(profile("gputoolsd"),decision("allow"),operation("mach-priv-task-port"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("network-outbound"),filters([literal("/private/var/run/gputoolsdhelper.sock")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("network-outbound"),filters([regex("^/private/var/run/lockdown/checkin"/i)])).
profileRule(profile("gputoolsd"),decision("allow"),operation("network-outbound"),filters([local(tcp("localhost:*"))])).
profileRule(profile("gputoolsd"),decision("allow"),operation("network-outbound"),filters([literal("/private/var/run/syslog")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("network-outbound"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/tmp/launchd-[0-9]+[.][^/]+/sock$"/i))])).
profileRule(profile("gputoolsd"),decision("allow"),operation("privSTAR"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("priv-adjtime"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("priv-netinetSTAR"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("priv-netinet-reservedport"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("process-exec"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/Developer/usr/libexec/gputoolsd")])).
profileRule(profile("gputoolsd"),decision("allow"),operation("process-infoSTAR"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("process-info-listpids"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("process-info-pidinfo"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("process-info-pidfdinfo"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("process-info-pidfileportinfo"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("process-info-setcontrol"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("process-info-dirtycontrol"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("process-info-rusage"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("pseudo-tty"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("signal"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("sysctl-read"),filters([])).
profileRule(profile("gputoolsd"),decision("allow"),operation("system-sched"),filters([require-entitlement("com.apple.private.kernel.override-cpumon",[])])).
