

profileDefault(profile("Lowtide"),decision("deny")).
profileRule(profile("Lowtide"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/ptmx")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/dtracehelper")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/random")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/urandom")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/aes_0")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension-class("com.apple.quicklook.readonly")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension-class("com.apple.nsnetworkd.readonly")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension-class("com.apple.app-sandbox.read")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension-class("com.apple.app-sandbox.read-write")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Library/Caches/AppleTV/"),extension-class("com.apple.app-sandbox.read")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension("com.apple.librarian.ubiquity-container"),subpath("/private/var/mobile/Library/Mobile Documents/"),extension-class("com.apple.app-sandbox.read")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/zero")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/random")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/urandom")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/aes_0")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/ptmx")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/dtracehelper")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/Managed Preferences/mobile/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]lowtide[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/SyncedPreferences/com[.]apple[.]lowtide[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/SyncedPreferences/com[.]apple[.]lowtide-.+[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Caches/Snapshots/com[.]apple[.]lowtide-"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Caches/Snapshots/com[.]apple[.]lowtide/"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Caches/Snapshots/com[.]apple[.]lowtide$"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Documents/com[.]apple[.]lowtide[.]settings$"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Documents/com[.]apple[.]lowtide[.]settings/"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Saved Application State/com[.]apple[.]lowtide.savedState/"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Caches/com[.]apple[.]lowtide/"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Caches/com[.]apple[.]lowtide$"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.demo-settings.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.DataAccess.BehaviorOptions.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Media/com.apple.itunes.lock_sync")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Cookies")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Cookies/com.apple.itunesstored.2.sqlitedb")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Cookies/com.apple.itunesstored.2.sqlitedb-journal")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.itunesstored.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.mobileipod.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Media/iTunes_Control/iTunes")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Media/iTunes_Control/iTunes/MediaLibrary.sqlitedb")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Media/iTunes_Control/iTunes/MediaLibrary.sqlitedb-journal")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Media/iTunes_Control/iTunes/MediaLibrary.sqlitedb-shm")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Media/iTunes_Control/iTunes/MediaLibrary.sqlitedb-wal")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Caches/com.apple.iTunesStore/network-constraints.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Caches/com[.]apple[.]iTunesStore/ISURLBag/com[.]apple[.]lowtide$"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Caches/com[.]apple[.]iTunesStore/ISURLBag/com[.]apple[.]lowtide/$"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Caches/com[.]apple[.]iTunesStore/ISURLBag/com[.]apple[.]lowtide/.+$"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.persistentconnection.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Caches/.com.apple.persistentconnection.settings.lock.lock")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Logs/PersistentConnection/com[.]apple[.]lowtide"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Logs/CrashReporter/PersistentConnection/com[.]apple[.]lowtide"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Caches/com.apple.persistentconnection.intervalcache.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Caches/com.apple.persistentconnection.intervalcache.plist.lock")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.avfoundation.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.coreaudio.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.coremedia.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.corevideo.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.homesharing.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Caches/com.apple.itunesstored/url-resolution.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.SpeakSelection.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.voiceservices.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/VoiceServices/Assets/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Assets/com_apple_MobileAsset_VoiceServicesVocalizerVoice/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.mediaaccessibility.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.mediaaccessibility.public.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.MobileAsset.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Caches/com.apple.keyboards/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Keyboard/LocalDictionary")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.keyboard.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.InputModePreferences.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.assistant.support.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.Preferences.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Fonts/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/SystemConfiguration/com.apple.accounts.exists.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/SystemConfiguration/com.apple.sinaweibo.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/SystemConfiguration/com.apple.linkedin.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/SystemConfiguration/com.apple.facebook.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/SystemConfiguration/com.apple.twitter.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Caches/com.apple.IconsCache/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Caches/com.apple.UIStatusBar/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.Sharing.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.CoreMotion.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.Accessibility.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.UIKit.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.WebUI.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.mt.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.preferences.sounds.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.telephonyutilities.dialassist.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/.GlobalPreferences.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.logging.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.MapKit.internal.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/SystemConfiguration/com.apple.radios.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/com.apple.networkd.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/com.apple.NetworkStatistics.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Library/Dictionaries/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Dictionaries/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Caches/DateFormats.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.AppSupport.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.GEO.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.locationd.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.accountsd.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.appleaccount.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Cookies$"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Cookies/Cookies[.]binarycookies"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.WebFoundation.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Caches/com.apple.pep.configuration.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.ConfigServer.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Logs")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Logs/ADDataStore.sqlitedb")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Logs/ADDataStore.sqlitedb-journal")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.AdLib.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.CrashReporter.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.accountsettings.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.airplay.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.aggregated.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.appletvservices.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.celestial.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.iqagent.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.preferences-sounds.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.preferences.datetime.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.soundpref.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.storebookkeeper.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.youtubeframework.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.LaunchServices.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/SystemConfiguration/preferences.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/logs/CrashReporter/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/AppleInternal/Library/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Applications/AppleTV.app.dSYM/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Applications/AppleTV.app/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Application Support/Front Row/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/tmp/AirTunes/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]frontrow[.]"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Logs/CrashReporter/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Cookies/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/ConfigurationProfiles/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Caches/com.apple.Radio/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Media/Radio/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.apsd.launchd")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Documents/var/nrd/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Logs/awd/awd-AppleTV.log"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.mmcs.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/MediaStream/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Logs/Ubiquity/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Caches/AppleTV/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/MobileSoftwareUpdate/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Updates/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Media/iTunes_Control/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/tmp/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/db/timezone/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/System/Library/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/usr/lib/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/usr/share/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/System/Library/Frameworks/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/System/Library/PrivateFrameworks/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/null")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([vnode-type(tty),regex("^/dev/ttyp[0-9a-f]$"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([vnode-type(tty),regex("^/dev/ptyp[0-9a-f]$"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([regex("^/dev/ttys[0-9]"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([regex("^/dev/ttys[0-9]+"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Mobile Documents/"),extension("com.apple.librarian.ubiquity-container")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Application Support/Ubiquity/genstore/"),extension("com.apple.librarian.ubiquity-revision")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Assets/"),extension("com.apple.assets.read")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Developer/"),debug-mode])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Developer/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Developer/"),require-not(require-entitlement("platform-application"))])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/tmp/"),debug-mode])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/tmp/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/XcodeBuiltProducts/"),debug-mode])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/XcodeBuiltProducts/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/dev/")),literal("/private/etc/protocols")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/dev/")),literal("/private/etc/services")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/dev/")),literal("/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/dev/")),literal("/private/var/mobile/Library/Caches/com.apple.MobileGestalt.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/dev/")),subpath("/private/var/mobile/Library/ConfigurationProfiles/PublicInfo/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/dev/")),literal("/private/etc/hosts")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/dev/")),literal("/private/etc/group")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/dev/")),literal("/private/etc/passwd")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-read-metadata"),filters([])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Library/Caches/com.apple.pep.configuration.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Library/Logs/ADDataStore.sqlitedb-journal")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Library/Logs")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Library/Logs/ADDataStore.sqlitedb")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/Library/Application Support/Front Row")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/tmp/MediaControlServer.log")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Library/Caches/com.apple.iLifeSlideshow/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Library/Application Support")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/db/timezone/localtime")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Library/Application Support/Front Row/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/AirTunes/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Library/Logs/CrashReporter/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Library/Cookies/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Library/ConfigurationProfiles/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Library/Caches/com.apple.Radio/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Media/Radio/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Library/Preferences/com.apple.apsd.launchd")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Documents/var/nrd/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Library/MediaStream/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Library/Logs/Ubiquity/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Library/Caches/AppleTV/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/MobileSoftwareUpdate/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Media/iTunes_Control/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]mmcs[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Logs/awd/awd-AppleTV.log"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]MobileAsset[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]frontrow[.]"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/[.]GlobalPreferences[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]AdLib[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]CrashReporter[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]accountsettings[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]airplay[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]aggregated[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]appletvservices[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]celestial[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]coremedia[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]demo-settings[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]itunesstored[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]iqagent[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]mediaaccessibility[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]preferences-sounds[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]preferences[.]datetime[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]soundpref[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]storebookkeeper[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]voiceservices[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]youtubeframework[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Cookies$"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Cookies/Cookies[.]binarycookies"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/"),debug-mode])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/dev/ptmx")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/dev/dtracehelper")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Media/com.apple.itunes.lock_sync")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]lowtide[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/Snapshots/com[.]apple[.]lowtide-"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/Snapshots/com[.]apple[.]lowtide/"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/Snapshots/com[.]apple[.]lowtide$"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Documents/com[.]apple[.]lowtide[.]settings$"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Documents/com[.]apple[.]lowtide[.]settings/"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Saved Application State/com[.]apple[.]lowtide.savedState/"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/com[.]apple[.]lowtide/"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/com[.]apple[.]lowtide$"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Library/Cookies/com.apple.itunesstored.2.sqlitedb-journal")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Library/Cookies")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Library/Cookies/com.apple.itunesstored.2.sqlitedb")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Media/iTunes_Control/iTunes/MediaLibrary.sqlitedb-journal")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]mobileipod[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]itunesstored[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Media/iTunes_Control/iTunes")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Media/iTunes_Control/iTunes/MediaLibrary.sqlitedb")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Media/iTunes_Control/iTunes/MediaLibrary.sqlitedb-shm")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Media/iTunes_Control/iTunes/MediaLibrary.sqlitedb-wal")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Library/Caches/com.apple.iTunesStore/network-constraints.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/com[.]apple[.]iTunesStore/ISURLBag/com[.]apple[.]lowtide$"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/com[.]apple[.]iTunesStore/ISURLBag/com[.]apple[.]lowtide/$"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/com[.]apple[.]iTunesStore/ISURLBag/com[.]apple[.]lowtide/.+$"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Library/Caches/.com.apple.persistentconnection.settings.lock.lock")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Logs/PersistentConnection/com[.]apple[.]lowtide"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Logs/CrashReporter/PersistentConnection/com[.]apple[.]lowtide"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Library/Caches/com.apple.persistentconnection.intervalcache.plist")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Library/Caches/com.apple.persistentconnection.intervalcache.plist.lock")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),subpath("/private/var/mobile/Library/Caches/com.apple.keyboards/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]mediaaccessibility[.]public[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Library/Keyboard/LocalDictionary")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Preferences[.]plist"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/dev/aes_0")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),vnode-type(tty),regex("^/dev/ttyp[0-9a-f]$"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),vnode-type(tty),regex("^/dev/ptyp[0-9a-f]$"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/dev/ttys[0-9]"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/dev/ttys[0-9]+"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),vnode-type(directory),literal("/private/var/mobile/Media/iTunes_Control/iTunes")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),subpath("/private/var/mobile/Library/Mobile Documents/"),extension("com.apple.librarian.ubiquity-container")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),require-not(literal("/dev/urandom")),require-not(literal("/dev/random")),literal("/dev/zero")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),require-not(literal("/dev/urandom")),require-not(literal("/dev/random")),literal("/dev/null")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Documents")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Documents/var")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(directory),literal("/private/var/mobile/Media")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(directory),literal("/private/var/mobile/Library/Caches/com.apple.DictionaryServices")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),literal("/private/var/mobile/Library/Caches")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),literal("/private/var/mobile/Library/Saved Application State")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),regex("^/private/var/mobile/Library/Saved Application State/com[.]apple[.]lowtide.savedState"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),literal("/private/var/mobile/Library/Caches/Snapshots")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),literal("/private/var/mobile/Library/com.apple.iTunesStore")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),literal("/private/var/mobile/Library/com.apple.iTunesStore/LocalStorage")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),literal("/private/var/mobile/Library/Caches/com.apple.iTunesStore")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),literal("/private/var/mobile/Library/Caches/com.apple.iTunesStore/ISURLBag")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),literal("/private/var/mobile/Library/Logs/PersistentConnection")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),literal("/private/var/mobile/Library/Logs/CrashReporter/PersistentConnection")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(regular-file),extension("com.apple.private.safe-move.send")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Media/iTunes_Control/iTunes/MediaLibrary.sqlitedb")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Library/Logs/ADDataStore.sqlitedb")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Library/Cookies/com.apple.itunesstored.2.sqlitedb")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(regular-file),extension("com.apple.private.safe-move.send")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-write-flags"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Media")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-write-mode"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Media")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-write-unlink"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Updates/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("file-write-unlink"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(regular-file),extension("com.apple.private.safe-move.receive")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleJPEGDriverUserClient")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOMobileFramebufferUserClient")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOSurfaceRootUserClient")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOSurfaceSendRight")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleM2ScalerCSCDriverUserClient")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleKeyStoreUserClient")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelSharedUserClient2")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelContext")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelDevice")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelSharedUserClient")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelContext2")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelDevice2")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleNANDFTLUserClient")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("com_apple_driver_FairPlayIOKitUserClient")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("RootDomainUserClient")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IODPServiceUserClient")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IODPDisplayInterfaceUserClient")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IODPDeviceUserClient")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IODPControllerUserClient")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IODPAudioInterfaceUserClient")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAVServiceUserClient")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAVVideoInterfaceUserClient")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAVDeviceUserClient")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAVControllerUserClient")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAVAudioInterfaceUserClient")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleMobileFileIntegrityUserClient")])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-set-properties"),filters([])).
profileRule(profile("Lowtide"),decision("allow"),operation("iokit-get-properties"),filters([])).
profileRule(profile("Lowtide"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^/FSM-"/i),debug-mode])).
profileRule(profile("Lowtide"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^OA-"/i),debug-mode])).
profileRule(profile("Lowtide"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^stack-logs"/i),debug-mode])).
profileRule(profile("Lowtide"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-c$"/i),debug-mode])).
profileRule(profile("Lowtide"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-s$"/i),debug-mode])).
profileRule(profile("Lowtide"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^/FSM-"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("Lowtide"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^OA-"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("Lowtide"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^stack-logs"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("Lowtide"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-c$"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("Lowtide"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-s$"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("Lowtide"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^/FSM-"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("Lowtide"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^OA-"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("Lowtide"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^stack-logs"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("Lowtide"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-c$"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("Lowtide"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-s$"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("Lowtide"),decision("allow"),operation("ipc-posix-shm-readSTAR"),filters([ipc-posix-name-regex("^Apple MIDI in [0-9]+$"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("ipc-posix-shm-readSTAR"),filters([ipc-posix-name-regex("^Apple MIDI out [0-9]+$"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("ipc-posix-shm-readSTAR"),filters([ipc-posix-name("apple.shm.notification_center")])).
profileRule(profile("Lowtide"),decision("allow"),operation("ipc-posix-shm-write-data"),filters([ipc-posix-name-regex("^Apple MIDI in [0-9]+$"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("ipc-posix-shm-write-data"),filters([ipc-posix-name-regex("^Apple MIDI out [0-9]+$"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("ipc-posix-shm-write-data"),filters([ipc-posix-name("apple.shm.notification_center")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-bootstrap"),filters([])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.xpcd")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.tccd")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.mobilegestalt.xpc")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.lsd")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.backboard.processassertionconnection")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.system.logger")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.system.notification_center")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.distributed_notifications@1v3")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.managedconfiguration.profiled.public")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.itunesstored.xpc")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.apsd")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.backboard.systemservices")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.librariand")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name-regex("^com.apple.uikit.viewservice..+"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.mediaserverd")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coremedia.videocompositor")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coremedia.sandboxserver")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coremedia.remaker")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coremedia.recorder")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coremedia.endpoint")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coremedia.assetimagegenerator")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coremedia.asset")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coremedia.admin")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.audio.AudioSession")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.springboard.backgroundappservices")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.itunescloudd.xpc")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.audio.AURemoteIOServer")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("ScripterServer")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.TextInput")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.TextInput.rdt")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.accessibility.gax.backboard")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("UIASTNotificationCenter")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name-regex("^com[.]apple[.]accessibility[.]gax[.]client-"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name-regex("^com[.]apple[.]assistant[.]contextprovider[.]"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.accessibility.AXBackBoardServer")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.audio.AudioQueueServer")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.voiceservices.tts")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.mobileassetd")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.airplaydiagnostics.server")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.assistant.dictation")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.dictationd.recognition")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.UIKit.pasteboardd")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.CARenderServer")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.springboard.services")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.iphone.axserver-systemwide")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.iohideventsystem")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.backboard.hid.services")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.backboard.display.services")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.UIKit.statusbarserver")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.sharingd")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.marco")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.configd")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.NetworkInformation")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.PPPController")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.DNSConfiguration")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.SCNetworkReachability")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.commcenter.xpc")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.commcenter.cupolicy.xpc")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.usymptomsd")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.symptomsd")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.appsupport.cplogd")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.cvmsServ")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.gpumemd.source")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.locationd.registration")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.locationd.synchronous")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.locationd.spi")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.iTunesStore.daemon")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.iTunesStore.daemon.deatchwatch")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.iTunesStore.daemon-notifications")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.accountsd.accountmanager")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.MediaRemote.daemon")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.MediaRemote.nowplayingserver")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.MediaRemote.isrunning")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.networkd")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.nsnetworkd")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.cfnetwork.AuthBrokerAgent")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.cfnetwork.cfnetworkagent")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.mobile.installd")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.medialibraryd.xpc")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("PurplePPTServer")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([local-name("com.apple.coremedia.customurlhandler")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.frontrow.tracerouteix")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.atvitunescloudd.xpc")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.wirelessproxd")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.wifi.manager")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.voiceservices.keepalive")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.tzlink")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.timed.xpc")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.springboard.processinvalidation")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.server.bluetooth.xpc")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.server.bluetooth")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.securityd")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.mobile.softwareupdated")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.mobile.obliteration")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.managedconfiguration.profiled")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.fig.movie")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.fairplayd.versioned")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.fairplayd")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coresymbolicationd")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coremedia.videoqueue")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coremedia.wirelessdisplay")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coremedia.formatreaderloader")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coremedia.formatreader")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coremedia.cpe")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.backboard.workspaceserverconnection")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.backboard.checkin")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.adid")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.aggregated.addaily")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.aggregated")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.helper")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.PowerManagement.control")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.CrashCopy.OTA")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("PurpleWorkspacePort")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("PurpleSystemAppPort")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.awdd")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.absd")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coreservices.appleid.authentication")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.absinthed")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.hangtracerd")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.ReportCrash.SimulateCrash")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.itunesstored.xpc"),require-entitlement("com.apple.itunesstored.private",[])])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-register"),filters([global-name("com.apple.SBUserNotification")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-register"),filters([global-name("PurpleSystemAppPort")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-register"),filters([global-name("com.apple.airplay.xpc")])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-register"),filters([global-name-regex("^com[.]apple[.]appletv$"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-register"),filters([global-name-regex("^com[.]apple[.]appletv[.]"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-register"),filters([global-name-regex("^com[.]apple[.]lowtide$"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-register"),filters([global-name-regex("^com[.]apple[.]lowtide[.]"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-register"),filters([global-name-regex("^com[.]apple[.]accessibility[.]gax[.]client-"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-register"),filters([global-name-regex("^com[.]apple[.]assistant[.]contextprovider[.]"/i)])).
profileRule(profile("Lowtide"),decision("allow"),operation("mach-register"),filters([local-name("com.apple.iphone.axserver")])).
profileRule(profile("Lowtide"),decision("allow"),operation("network-inbound"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/"))])).
profileRule(profile("Lowtide"),decision("allow"),operation("network-outbound"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/tmp/launchd-[0-9]+[.][^/]+/sock$"/i))])).
profileRule(profile("Lowtide"),decision("allow"),operation("privSTAR"),filters([])).
profileRule(profile("Lowtide"),decision("allow"),operation("priv-adjtime"),filters([])).
profileRule(profile("Lowtide"),decision("allow"),operation("priv-netinetSTAR"),filters([])).
profileRule(profile("Lowtide"),decision("allow"),operation("priv-netinet-reservedport"),filters([])).
profileRule(profile("Lowtide"),decision("allow"),operation("process-exec"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/Applications/AppleTV.app/")])).
profileRule(profile("Lowtide"),decision("allow"),operation("process-infoSTAR"),filters([])).
profileRule(profile("Lowtide"),decision("allow"),operation("process-info-listpids"),filters([])).
profileRule(profile("Lowtide"),decision("allow"),operation("process-info-pidinfo"),filters([])).
profileRule(profile("Lowtide"),decision("allow"),operation("process-info-pidfdinfo"),filters([])).
profileRule(profile("Lowtide"),decision("allow"),operation("process-info-pidfileportinfo"),filters([])).
profileRule(profile("Lowtide"),decision("allow"),operation("process-info-setcontrol"),filters([])).
profileRule(profile("Lowtide"),decision("allow"),operation("process-info-dirtycontrol"),filters([])).
profileRule(profile("Lowtide"),decision("allow"),operation("process-info-rusage"),filters([])).
profileRule(profile("Lowtide"),decision("allow"),operation("pseudo-tty"),filters([])).
profileRule(profile("Lowtide"),decision("allow"),operation("signal"),filters([target(self)])).
profileRule(profile("Lowtide"),decision("allow"),operation("sysctl-read"),filters([])).
profileRule(profile("Lowtide"),decision("allow"),operation("system-fsctl"),filters([])).
profileRule(profile("Lowtide"),decision("allow"),operation("system-info"),filters([info-type("net.link.addr")])).
profileRule(profile("Lowtide"),decision("allow"),operation("system-info"),filters([info-type("hw.uuid")])).
profileRule(profile("Lowtide"),decision("allow"),operation("system-sched"),filters([require-entitlement("com.apple.private.kernel.override-cpumon",[])])).
profileRule(profile("Lowtide"),decision("allow"),operation("system-socket"),filters([socket-domain(af_route)])).
profileRule(profile("Lowtide"),decision("allow"),operation("system-socket"),filters([socket-domain(af_system),socket-protocol(2)])).
