

profileDefault(profile("MailCompositionService"),decision("deny")).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/ptmx")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/dtracehelper")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/aes_0")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension-class("com.apple.quicklook.readonly")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension-class("com.apple.nsnetworkd.readonly")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension-class("com.apple.app-sandbox.read")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension-class("com.apple.app-sandbox.read-write")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension("com.apple.librarian.ubiquity-container"),subpath("/private/var/mobile/Library/Mobile Documents/"),extension-class("com.apple.app-sandbox.read")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/MediaCache/"),extension-class("com.apple.app-sandbox.read")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.carrier.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Carrier Bundles/Overlay/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/Managed Preferences/mobile/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.AOSNotification.public.notbackedup.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.dataaccess.launchd")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.avfoundation.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.coreaudio.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.coremedia.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.corevideo.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.homesharing.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.itunesstored.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Caches/com.apple.itunesstored/url-resolution.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.SpeakSelection.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.voiceservices.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/VoiceServices/Assets/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Assets/com_apple_MobileAsset_VoiceServicesVocalizerVoice/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.mediaaccessibility.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.mediaaccessibility.public.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.MobileAsset.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Caches/com.apple.keyboards/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Keyboard/LocalDictionary")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.keyboard.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.InputModePreferences.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.assistant.support.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.Preferences.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Fonts/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/SystemConfiguration/com.apple.accounts.exists.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/SystemConfiguration/com.apple.sinaweibo.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/SystemConfiguration/com.apple.linkedin.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/SystemConfiguration/com.apple.facebook.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/SystemConfiguration/com.apple.twitter.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Caches/com.apple.IconsCache/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Caches/com.apple.UIStatusBar/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.Sharing.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.CoreMotion.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.Accessibility.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.UIKit.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.WebUI.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.mt.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.preferences.sounds.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.telephonyutilities.dialassist.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/.GlobalPreferences.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.logging.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.MapKit.internal.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/SystemConfiguration/com.apple.radios.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/com.apple.networkd.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/com.apple.NetworkStatistics.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Library/Dictionaries/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Dictionaries/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Caches/DateFormats.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.accountsd.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.appleaccount.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.WebFoundation.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.mail.composition.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.mobilemail.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Applications/MailCompositionService.app/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.bulletinboard.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/tmp/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/db/timezone/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/System/Library/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/usr/lib/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/usr/share/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/System/Library/Frameworks/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/System/Library/PrivateFrameworks/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Cookies$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Cookies/Cookies[.]binarycookies"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([regex("^/System/Library/Carrier Bundles//carrier[.]plist$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([regex("^/System/Library/Carrier Bundles/.+/carrier[.]plist$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Carrier Bundles//carrier[.]plist$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Carrier Bundles/.+/carrier[.]plist$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([regex("^/System/Library/Carrier Bundles/[.]png$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([regex("^/System/Library/Carrier Bundles/.+[.]png$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Carrier Bundles/[.]png$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Carrier Bundles/.+[.]png$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Mobile Documents/"),extension("com.apple.librarian.ubiquity-container")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Application Support/Ubiquity/genstore/"),extension("com.apple.librarian.ubiquity-revision")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Assets/"),extension("com.apple.assets.read")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Developer/"),debug-mode])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Developer/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Developer/"),require-not(require-entitlement("platform-application"))])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/tmp/"),debug-mode])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/tmp/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/XcodeBuiltProducts/"),debug-mode])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/XcodeBuiltProducts/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Preferences/com.apple.PeoplePicker.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Preferences/com.apple.AOSNotification.public.notbackedup.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Caches/Checkpoint.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),subpath("/private/var/tmp/MediaCache/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Preferences/com.apple.coreaudio.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Preferences/com.apple.coremedia.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Preferences/com.apple.corevideo.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Preferences/com.apple.homesharing.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Preferences/com.apple.itunesstored.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/preferences/com.apple.networkd.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/preferences/com.apple.NetworkStatistics.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Media/iTunes_Control/iTunes/Ringtones.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),subpath("/private/var/mobile/Media/Purchases/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),subpath("/private/var/mobile/Media/iTunes_Control/Ringtones/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Media/com.apple.itunes.lock_sync")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),subpath("/private/var/Managed Preferences/mobile/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Preferences/com.apple.avfoundation.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Preferences/com.apple.mobileslideshow.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Preferences/com.apple.camera.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Preferences/com.apple.springboard.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),subpath("/Library/Ringtones/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Media/Vibrations/UserGeneratedVibrationPatterns.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]MailCompositionService[.]plist"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),regex("^/private/var/mobile/Library/SyncedPreferences/com[.]apple[.]MailCompositionService[.]plist"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),regex("^/private/var/mobile/Library/SyncedPreferences/com[.]apple[.]MailCompositionService-.+[.]plist"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),regex("^/private/var/mobile/Library/Caches/Snapshots/com[.]apple[.]MailCompositionService-"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),regex("^/private/var/mobile/Library/Caches/Snapshots/com[.]apple[.]MailCompositionService/"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),regex("^/private/var/mobile/Library/Caches/Snapshots/com[.]apple[.]MailCompositionService$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),regex("^/private/var/mobile/Documents/com[.]apple[.]MailCompositionService[.]settings$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),regex("^/private/var/mobile/Documents/com[.]apple[.]MailCompositionService[.]settings/"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),regex("^/private/var/mobile/Library/Saved Application State/com[.]apple[.]MailCompositionService.savedState/"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),regex("^/private/var/mobile/Library/Caches/com[.]apple[.]MailCompositionService/"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),regex("^/private/var/mobile/Library/Caches/com[.]apple[.]MailCompositionService$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Preferences/com.apple.demo-settings.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Preferences/com.apple.DataAccess.BehaviorOptions.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),regex("^/private/var/mobile/Library/Cookies$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),regex("^/private/var/mobile/Library/Cookies/Cookies[.]binarycookies"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Preferences/com.apple.WebFoundation.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Caches/com.apple.itunesstored/url-resolution.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Preferences/com.apple.AppSupport.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Preferences/com.apple.GEO.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Preferences/com.apple.locationd.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/WebKit/LocalStorage")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/WebKit/LocalStorage/StorageTracker.db")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/WebKit/LocalStorage/StorageTracker.db-journal")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),subpath("/private/var/mobile/Library/WebKit/LocalStorage/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/WebKit/Databases")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/WebKit/Databases/Databases.db")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/WebKit/Databases/Databases.db-journal")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Preferences/com.apple.Preferences.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Preferences/com.apple.youtubeframework.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Preferences/com.apple.aggregated.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Preferences/com.apple.mobileipod.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Preferences/com.apple.WebKit.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Preferences/com.apple.videos.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),subpath("/private/var/mobile/Library/WebKit/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),subpath("/private/var/mobile/Media/Safari/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),subpath("/private/var/mobile/Library/WebClips/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),literal("/dev/zero")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),literal("/dev/random")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),literal("/dev/urandom")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),literal("/dev/aes_0")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),literal("/dev/ptmx")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),literal("/dev/dtracehelper")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),literal("/dev/null")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),vnode-type(tty),regex("^/dev/ttyp[0-9a-f]$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),vnode-type(tty),regex("^/dev/ptyp[0-9a-f]$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),regex("^/dev/ttys[0-9]"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),regex("^/dev/ttys[0-9]+"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),require-not(subpath("/dev/")),literal("/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),require-not(subpath("/dev/")),literal("/private/var/mobile/Library/Caches/com.apple.MobileGestalt.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),require-not(subpath("/dev/")),subpath("/private/var/mobile/Library/ConfigurationProfiles/PublicInfo/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),require-not(subpath("/dev/")),literal("/private/etc/hosts")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),require-not(subpath("/dev/")),literal("/private/etc/group")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),require-not(subpath("/dev/")),literal("/private/etc/passwd")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),require-not(subpath("/dev/")),literal("/private/etc/protocols")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),require-not(subpath("/dev/")),literal("/private/etc/services")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),subpath("/private/var/mobile/Media/PhotoData/Metadata/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),subpath("/private/var/mobile/Media/PhotoData/Sync/FaceAlbumThumbnails/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),subpath("/private/var/mobile/Media/PhotoData/Thumbnails/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Media/PhotoData/syncInfo.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),regex("^/private/var/mobile/Media/PhotoData/Photos.sqlite$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),regex("^/private/var/mobile/Media/PhotoData/Photos.sqlite-wal$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),regex("^/private/var/mobile/Media/PhotoData/Photos.sqlite-shm$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),regex("^/private/var/mobile/Media/PhotoData/Photos.sqlite-journal$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),extension("com.apple.tcc.kTCCServicePhotos")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),literal("/private/var/mobile/Library/Preferences/com.apple.mobilephone.speeddial.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),subpath("/private/var/mobile/Library/AddressBook/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/private/var/mobile/Library/Carrier Bundles/")),require-not(subpath("/System/Library/Carrier Bundles/")),extension("com.apple.tcc.kTCCServiceAddressBook")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-read-metadata"),filters([])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-read-xattr"),filters([literal("/private/var/mobile/Library/Caches")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]mail[.]composition[.]plist"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Cookies$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Cookies/Cookies[.]binarycookies"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/"),debug-mode])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Library/WebKit/LocalStorage/StorageTracker.db-journal")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Cookies$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Cookies/Cookies[.]binarycookies"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]MailCompositionService[.]plist"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/Snapshots/com[.]apple[.]MailCompositionService-"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/Snapshots/com[.]apple[.]MailCompositionService/"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/Snapshots/com[.]apple[.]MailCompositionService$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Documents/com[.]apple[.]MailCompositionService[.]settings$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Documents/com[.]apple[.]MailCompositionService[.]settings/"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Saved Application State/com[.]apple[.]MailCompositionService.savedState/"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/com[.]apple[.]MailCompositionService/"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/com[.]apple[.]MailCompositionService$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Library/WebKit/LocalStorage")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Library/WebKit/LocalStorage/StorageTracker.db")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),subpath("/private/var/mobile/Library/WebKit/LocalStorage/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Library/WebKit/Databases/Databases.db-journal")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Library/WebKit/Databases")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Library/WebKit/Databases/Databases.db")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),subpath("/private/var/mobile/Library/WebKit/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Preferences[.]plist"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]youtubeframework[.]plist"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]WebFoundation[.]plist"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),subpath("/private/var/mobile/Media/Safari/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),subpath("/private/var/mobile/Library/WebClips/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Media/com.apple.itunes.lock_sync")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),subpath("/private/var/tmp/MediaCache/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]mobileslideshow[.]plist"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]PeoplePicker[.]plist"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Library/Preferences/com.apple.dataaccess.launchd")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),subpath("/private/var/mobile/Library/Caches/com.apple.keyboards/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]mediaaccessibility[.]public[.]plist"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Library/Keyboard/LocalDictionary")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Preferences[.]plist"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),subpath("/private/var/mobile/Library/Mobile Documents/"),extension("com.apple.librarian.ubiquity-container")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),require-not(subpath("/private/var/mobile/Media/")),literal("/dev/ptmx")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),require-not(subpath("/private/var/mobile/Media/")),literal("/dev/dtracehelper")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),require-not(subpath("/private/var/mobile/Media/")),literal("/dev/aes_0")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),require-not(subpath("/private/var/mobile/Media/")),vnode-type(tty),regex("^/dev/ttyp[0-9a-f]$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),require-not(subpath("/private/var/mobile/Media/")),vnode-type(tty),regex("^/dev/ptyp[0-9a-f]$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),require-not(subpath("/private/var/mobile/Media/")),regex("^/dev/ttys[0-9]"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),require-not(subpath("/private/var/mobile/Media/")),regex("^/dev/ttys[0-9]+"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),require-not(subpath("/private/var/mobile/Media/")),require-not(literal("/dev/urandom")),require-not(literal("/dev/random")),literal("/dev/zero")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),require-not(subpath("/private/var/mobile/Media/")),require-not(literal("/dev/urandom")),require-not(literal("/dev/random")),literal("/dev/null")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Library/Preferences/com.apple.mobilephone.speeddial.plist")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),subpath("/private/var/mobile/Library/AddressBook/")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),extension("com.apple.tcc.kTCCServiceAddressBook")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(directory),literal("/private/var/mobile/Library/Caches/com.apple.DictionaryServices")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),literal("/private/var/mobile/Library/Caches")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),literal("/private/var/mobile/Library/Saved Application State")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),regex("^/private/var/mobile/Library/Saved Application State/com[.]apple[.]MailCompositionService.savedState"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),literal("/private/var/mobile/Library/Caches/Snapshots")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(regular-file),extension("com.apple.private.safe-move.send")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Library/WebKit/LocalStorage/StorageTracker.db")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Library/WebKit/Databases/Databases.db")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(regular-file),extension("com.apple.private.safe-move.send")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("file-write-unlink"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(regular-file),extension("com.apple.private.safe-move.receive")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOSurfaceRootUserClient")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleJPEGDriverUserClient")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOMobileFramebufferUserClient")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOSurfaceSendRight")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleM2ScalerCSCDriverUserClient")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleKeyStoreUserClient")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelSharedUserClient2")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelContext")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelDevice")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelSharedUserClient")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelContext2")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelDevice2")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleMobileFileIntegrityUserClient")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("iokit-get-properties"),filters([])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^/FSM-"/i),debug-mode])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^OA-"/i),debug-mode])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^stack-logs"/i),debug-mode])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-c$"/i),debug-mode])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-s$"/i),debug-mode])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^/FSM-"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^OA-"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^stack-logs"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-c$"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-s$"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^/FSM-"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^OA-"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^stack-logs"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-c$"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-s$"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("ipc-posix-shm-readSTAR"),filters([ipc-posix-name-regex("^Apple MIDI in [0-9]+$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("ipc-posix-shm-readSTAR"),filters([ipc-posix-name-regex("^Apple MIDI out [0-9]+$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("ipc-posix-shm-readSTAR"),filters([ipc-posix-name("apple.shm.notification_center")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("ipc-posix-shm-write-data"),filters([ipc-posix-name-regex("^Apple MIDI in [0-9]+$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("ipc-posix-shm-write-data"),filters([ipc-posix-name-regex("^Apple MIDI out [0-9]+$"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("ipc-posix-shm-write-data"),filters([ipc-posix-name("apple.shm.notification_center")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-bootstrap"),filters([])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.xpcd")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.tccd")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.mobilegestalt.xpc")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.lsd")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.backboard.processassertionconnection")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.system.logger")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.system.notification_center")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.distributed_notifications@1v3")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.managedconfiguration.profiled.public")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.mobilecheckpoint.checkpointd")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.PersistentURLTranslator.Gatekeeper")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.vibrationmanagerd")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.locationd.registration")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.locationd.synchronous")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.locationd.spi")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.cmfsyncagent.embedded.auth")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.identityservicesd.idquery.embedded.auth")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.ABDatabaseDoctor")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.assetsd.changehub")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.imagent.embedded.auth")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.imagent.Embedded.Launched")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.fig.movie")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coremedia.sandboxserver")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coremedia.recorder")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coremedia.audiodeviceclock")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coremedia.asset")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coremedia.admin")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coremedia.assetimagegenerator")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SBUserNotification")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.mediaserverd")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coremedia.videocompositor")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coremedia.remaker")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coremedia.endpoint")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.audio.AudioSession")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.springboard.backgroundappservices")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.itunescloudd.xpc")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.itunesstored.xpc")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.MediaRemote.daemon")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.MediaRemote.nowplayingserver")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.MediaRemote.isrunning")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.audio.AURemoteIOServer")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.webinspector")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.securityd")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.webfilterd")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.WebBookmarks.webbookmarksd")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.safarifetcherd")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.configd")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.NetworkInformation")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.PPPController")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.DNSConfiguration")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.SCNetworkReachability")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.commcenter.xpc")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.commcenter.cupolicy.xpc")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.usymptomsd")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.symptomsd")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.networkd")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.nsnetworkd")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.cfnetwork.AuthBrokerAgent")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.cfnetwork.cfnetworkagent")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.backboard.systemservices")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.librariand")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name-regex("^com.apple.uikit.viewservice..+"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("ScripterServer")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.TextInput")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.TextInput.rdt")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.accessibility.gax.backboard")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("UIASTNotificationCenter")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name-regex("^com[.]apple[.]accessibility[.]gax[.]client-"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name-regex("^com[.]apple[.]assistant[.]contextprovider[.]"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.accessibility.AXBackBoardServer")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.audio.AudioQueueServer")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.voiceservices.tts")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.mobileassetd")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.airplaydiagnostics.server")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.assistant.dictation")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.dictationd.recognition")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.UIKit.pasteboardd")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.CARenderServer")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.springboard.services")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.iphone.axserver-systemwide")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.iohideventsystem")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.backboard.hid.services")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.backboard.display.services")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.UIKit.statusbarserver")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.sharingd")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.marco")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.appsupport.cplogd")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.cvmsServ")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.gpumemd.source")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([local-name("com.apple.iphone.axserver")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.accountsd.accountmanager")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("PurpleSystemAppPort")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.wifi.manager")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name-regex("^com[.]apple[.]dataaccess[.]dataaccessd"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.springboard")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.mobilemail.services.xpc")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.corerecents.recentsd")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("PurpleWorkspacePort")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.bulletinboard.utilitiesconnection")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.mediastream.sharing")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.backboard.applicationstateconnection")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.hangtracerd")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.ReportCrash.SimulateCrash")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.aggregated")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.itunesstored.xpc"),require-entitlement("com.apple.itunesstored.private",[])])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-register"),filters([local-name("com.apple.iphone.axserver")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-register"),filters([global-name-regex("^com[.]apple[.]accessibility[.]gax[.]client-"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("mach-register"),filters([global-name-regex("^com[.]apple[.]assistant[.]contextprovider[.]"/i)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("network-outbound"),filters([control-name("com.apple.network.statistics")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("network-outbound"),filters([control-name("com.apple.netsrc")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("network-outbound"),filters([literal("/private/var/run/mDNSResponder")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("network-outbound"),filters([remote(tcp("*:*"))])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("network-outbound"),filters([literal("/private/var/run/lockdown.sock")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("network-outbound"),filters([literal("/private/var/run/printd")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("network-outbound"),filters([literal("/private/var/run/syslog")])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("network-outbound"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/tmp/launchd-[0-9]+[.][^/]+/sock$"/i))])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("privSTAR"),filters([])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("priv-adjtime"),filters([])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("priv-netinetSTAR"),filters([])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("priv-netinet-reservedport"),filters([])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("process-infoSTAR"),filters([])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("process-info-listpids"),filters([])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("process-info-pidinfo"),filters([])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("process-info-pidfdinfo"),filters([])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("process-info-pidfileportinfo"),filters([])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("process-info-setcontrol"),filters([])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("process-info-dirtycontrol"),filters([])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("process-info-rusage"),filters([])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("pseudo-tty"),filters([])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("signal"),filters([target(self)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("sysctl-read"),filters([])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("system-sched"),filters([require-entitlement("com.apple.private.kernel.override-cpumon",[])])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("system-socket"),filters([socket-domain(af_route)])).
profileRule(profile("MailCompositionService"),decision("allow"),operation("system-socket"),filters([socket-domain(af_system),socket-protocol(2)])).
