

profileDefault(profile("mDNSResponder"),decision("deny")).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/dtracehelper")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/random")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/urandom")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/null")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/zero")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/dtracehelper")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/run/mDNSResponder")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/Managed Preferences/mobile")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/Library/Preferences/")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-readSTAR"),filters([literal("/Library/Managed Preferences")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/Managed Preferences/mobile/com.apple.mDNSResponder.plist")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/folders/[^/]+/[^/]+/-Caches-/mds/"/i)])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/folders/[^/]+/[^/]+/-Caches-/mds$"/i)])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/folders/[^/]+/[^/]+/C/mds/"/i)])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/folders/[^/]+/[^/]+/C/mds$"/i)])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/db/mds/[0-9]+/"/i)])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/db/mds/[0-9]+$"/i)])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/tmp/mds/[0-9]+/"/i)])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/tmp/mds/[0-9]+$"/i)])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-readSTAR"),filters([file-mode("#o0004"),subpath("/usr/lib/")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-readSTAR"),filters([file-mode("#o0004"),subpath("/System/")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-readSTAR"),filters([file-mode("#o0004"),subpath("/private/var/db/dyld/")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-readSTAR"),filters([file-mode("#o0004"),subpath("/usr/share/")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-read-data"),filters([subpath("/private/var/tmp/mds/")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-read-data"),filters([subpath("/private/var/db/mds/")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-read-data"),filters([literal("/private/var/db/crls/crlcache.db")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-read-data"),filters([literal("/Library/Keychains/System.keychain")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-read-data"),filters([require-not(regex("^/Library/Keychains/"/i)),literal("/usr/sbin")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-read-data"),filters([require-not(regex("^/Library/Keychains/"/i)),literal("/private/var/preferences/SystemConfiguration/preferences.plist")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-read-data"),filters([require-not(regex("^/Library/Keychains/"/i)),literal("/Library/Preferences/SystemConfiguration/com.apple.PowerManagement.plist")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-read-data"),filters([require-not(regex("^/Library/Keychains/"/i)),regex("^/Library/Preferences/com[.]apple[.]security[.]"/i)])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-read-data"),filters([require-not(regex("^/Library/Keychains/"/i)),literal("/Library/Security/Trust Settings/Admin.plist")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-read-data"),filters([require-not(regex("^/Library/Keychains/"/i)),literal("/Library/Preferences/com.apple.crypto.plist")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-read-data"),filters([require-not(regex("^/Library/Keychains/"/i)),regex("^/Library/Preferences/[.]GlobalPreferences[.]"/i)])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-read-data"),filters([require-not(regex("^/Library/Keychains/"/i)),regex("^/Library/Preferences/ByHost/[.]GlobalPreferences[.]"/i)])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-read-data"),filters([require-not(regex("^/Library/Keychains/"/i)),literal("/Library/Preferences/SystemConfiguration/com.apple.nat.plist")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-read-data"),filters([require-not(regex("^/Library/Keychains/"/i)),literal("/Library/Preferences/SystemConfiguration/preferences.plist")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-read-data"),filters([require-not(regex("^/Library/Keychains/"/i)),literal("/usr/sbin/mDNSResponder")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-read-data"),filters([require-not(regex("^/Library/Keychains/"/i)),literal("/dev/console")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-read-data"),filters([require-not(regex("^/Library/Keychains/"/i)),literal("/private/etc/hosts")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-read-data"),filters([require-not(regex("^/Library/Keychains/"/i)),literal("/private/etc")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-read-metadata"),filters([])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/run/mDNSResponder")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/folders/[^/]+/[^/]+/-Caches-/mds/"/i)])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/folders/[^/]+/[^/]+/-Caches-/mds$"/i)])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/folders/[^/]+/[^/]+/C/mds/"/i)])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/folders/[^/]+/[^/]+/C/mds$"/i)])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/db/mds/[0-9]+/"/i)])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/db/mds/[0-9]+$"/i)])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/tmp/mds/[0-9]+/"/i)])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/tmp/mds/[0-9]+$"/i)])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/cores/"/i),require-not(file-mode("#o0000"))])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/dtracehelper")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/console")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/null")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/zero")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("mDNSOffloadUserClient")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("wlDNSOffloadUserClient")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("RootDomainUserClient")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleMobileFileIntegrityUserClient")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("NVEthernetUserClientMDNS")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("iokit-get-properties"),filters([])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("ipc-posix-shm-readSTAR"),filters([])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("ipc-posix-shm-read-data"),filters([])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("ipc-posix-shm-read-metadata"),filters([])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("ipc-posix-shm-writeSTAR"),filters([])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("ipc-posix-shm-write-create"),filters([])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("ipc-posix-shm-write-data"),filters([])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("ipc-posix-shm-write-unlink"),filters([])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-bootstrap"),filters([])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.system.logger")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.system.notification_center")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.bsd.dirhelper")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.snhelper")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.mobilegestalt.xpc")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.blued")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.commcenter.cupolicy.xpc")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.wifi.manager")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.securityd")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.networkd")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.awacs")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.server.bluetooth")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.webcontentfilter.dns")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.system.logger")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.system.notification_center")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.NetworkInformation")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.DNSConfiguration")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.SCNetworkReachability")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.configd")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SecurityServer")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.mDNSResponderHelper")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.PowerManagement.control")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.ocspd")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.distributed_notifications.2")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.system.DirectoryService.libinfo_v1")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("mach-register"),filters([global-name("com.apple.d2d.ipc")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("networkSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/"))])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("network-outbound"),filters([literal("/private/var/run/asl_input")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("network-outbound"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/tmp/launchd-[0-9]+[.][^/]+/sock$"/i))])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("privSTAR"),filters([])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("priv-adjtime"),filters([])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("priv-netinetSTAR"),filters([])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("priv-netinet-reservedport"),filters([])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("process-infoSTAR"),filters([])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("process-info-listpids"),filters([])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("process-info-pidinfo"),filters([])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("process-info-pidfdinfo"),filters([])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("process-info-pidfileportinfo"),filters([])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("process-info-setcontrol"),filters([])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("process-info-dirtycontrol"),filters([])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("process-info-rusage"),filters([])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("signal"),filters([target(self)])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("signal"),filters([target(self)])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("sysctl-read"),filters([])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("system-info"),filters([info-type("net.link.addr")])).
profileRule(profile("mDNSResponder"),decision("allow"),operation("system-socket"),filters([])).
