

profileDefault(profile("mediaserverd"),decision("deny")).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/ptmx")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/dtracehelper")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/aes_0")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension-class("com.apple.app-sandbox.read-write")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension-class("com.apple.app-sandbox.read")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/zero")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/random")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/urandom")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/aes_0")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/ptmx")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/dtracehelper")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/Managed Preferences/mobile/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Cookies$"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Cookies/Cookies[.]binarycookies"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Caches/com[.]apple[.]mediaserverd/"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Caches/com[.]apple[.]mediaserverd$"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.WebFoundation.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.carrier.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([regex("^/System/Library/Carrier Bundles//carrier[.]plist$"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([regex("^/System/Library/Carrier Bundles/.+/carrier[.]plist$"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Carrier Bundles//carrier[.]plist$"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Carrier Bundles/.+/carrier[.]plist$"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([regex("^/System/Library/Carrier Bundles/[.]png$"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([regex("^/System/Library/Carrier Bundles/.+[.]png$"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Carrier Bundles/[.]png$"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Carrier Bundles/.+[.]png$"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Carrier Bundles/Overlay/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.AppSupport.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.GEO.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.locationd.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.Accessibility.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.VideoProcessing.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.audio.virtualaudio.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.CoreMotion.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.corevideo.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.ids.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.itunesstored.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.logging.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.mobileipod.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.preferences-sounds.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.preferences.sounds.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.settings.bluetooth.audio-route.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.springboard.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.VideoConference.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.celestial.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.conference.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.coreaudio.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.facetime.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.facetime.bag.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.imessage.bag.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.mediaaccessibility.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.mediaaccessibility.public.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/usr/sbin/mediaserverd")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/AppleInternal/Library/Preferences/com.apple.airplay.dashboard.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/SystemConfiguration/com.apple.mobilegestalt.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/usr/local/share/firmware/isp/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/usr/local/lib/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Library/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Developer/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/usr/sbin/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/tmp/MediaCache/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Logs/AirPlay[.]log"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Logs/CrashReporter/mediaserverd"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([extension("com.apple.app-sandbox.read-write")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([extension("com.apple.app-sandbox.read")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Media/Recordings/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Media/Purchases/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Media/Podcasts/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Media/PhotoStreamsData/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Media/PhotoData/Sync/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Media/iTunes_Control/Ringtones/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Media/iTunes_Control/Music/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Media/Downloads/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Media/DCIM/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/tmp/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Caches/com.apple.VideoConference/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/logs/mediaserverd/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/tmp/AirTunesHALPlugin.log")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.avfoundation.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.coremedia.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/wireless/Library/Logs/awd/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Caches/CoreMotion/CoreMotion.log")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.airplay.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Logs/awd/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/com.apple.networkd.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/com.apple.NetworkStatistics.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/AppleInternal/Library/Conference/Environments.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/db/timezone/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/System/Library/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/usr/lib/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/usr/share/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/.GlobalPreferences.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/System/Library/Frameworks/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/System/Library/PrivateFrameworks/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/null")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([vnode-type(tty),regex("^/dev/ttyp[0-9a-f]$"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([vnode-type(tty),regex("^/dev/ptyp[0-9a-f]$"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([regex("^/dev/ttys[0-9]"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([regex("^/dev/ttys[0-9]+"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Developer/"),debug-mode])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Developer/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Developer/"),require-not(require-entitlement("platform-application"))])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/tmp/"),debug-mode])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/tmp/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/XcodeBuiltProducts/"),debug-mode])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/XcodeBuiltProducts/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/dev/")),literal("/private/etc/group")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/dev/")),literal("/private/etc/passwd")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/dev/")),literal("/private/etc/protocols")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/dev/")),literal("/private/etc/services")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/dev/")),literal("/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/dev/")),literal("/private/var/mobile/Library/Caches/com.apple.MobileGestalt.plist")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/dev/")),subpath("/private/var/mobile/Library/ConfigurationProfiles/PublicInfo/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-readSTAR"),filters([require-not(subpath("/dev/")),literal("/private/etc/hosts")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-read-metadata"),filters([])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/ptmx")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/dtracehelper")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/MediaCache/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Logs/AirPlay[.]log"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Logs/CrashReporter/mediaserverd"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]mediaaccessibility[.]public[.]plist"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]audio[.]virtualaudio[.]plist"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]celestial[.]plist"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]conference[.]plist"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]coreaudio[.]plist"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]facetime[.]plist"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]facetime[.]bag[.]plist"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]imessage[.]bag[.]plist"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Cookies$"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Cookies/Cookies[.]binarycookies"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Caches/com[.]apple[.]mediaserverd/"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Caches/com[.]apple[.]mediaserverd$"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension("com.apple.app-sandbox.read-write")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension("com.apple.app-sandbox.read")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Media/Recordings/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Media/Purchases/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Media/Podcasts/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Media/PhotoStreamsData/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Media/PhotoData/Sync/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Media/iTunes_Control/Ringtones/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Media/iTunes_Control/Music/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Media/Downloads/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Media/DCIM/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Library/Caches/com.apple.VideoConference/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/logs/mediaserverd/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/tmp/AirTunesHALPlugin.log")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/wireless/Library/Logs/awd/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]avfoundation[.]plist"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]coremedia[.]plist"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Library/Caches/CoreMotion/CoreMotion.log")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Library/Logs/awd/")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]airplay[.]plist"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/aes_0")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(tty),regex("^/dev/ttyp[0-9a-f]$"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(tty),regex("^/dev/ptyp[0-9a-f]$"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/dev/ttys[0-9]"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/dev/ttys[0-9]+"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/"),debug-mode])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(literal("/dev/urandom")),require-not(literal("/dev/random")),literal("/dev/zero")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(literal("/dev/urandom")),require-not(literal("/dev/random")),literal("/dev/null")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(directory),literal("/private/var/mobile/Library/Caches/CoreMotion")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(regular-file),extension("com.apple.private.safe-move.send")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(directory),literal("/private/var/mobile/Library/Caches")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(directory),literal("/private/var/mobile/Library/Logs")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(regular-file),extension("com.apple.private.safe-move.send")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("file-write-unlink"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(regular-file),extension("com.apple.private.safe-move.receive")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelSharedUserClient2")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelContext")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelDevice")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelSharedUserClient")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelContext2")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelDevice2")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("com_apple_driver_FairPlayIOKitUserClient")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("RootDomainUserClient")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOUSBInterfaceUserClientV2")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOSurfaceSendRight")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOSurfaceRootUserClient")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOStreamAudioUserClient")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOMobileFramebufferUserClient")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOHIDResourceDeviceUserClient")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOHIDLibUserClient")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAudioCodecsUserClient")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAudio2TransformerUserClient")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAudio2DeviceUserClient")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccessoryManagerUserClient")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("H3H264VideoEncoderDriverUserClient")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleVXD393UserClient")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleVXD390UserClient")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleVXE380UserClient")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleVXD375UserClient")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleM2ScalerCSCDriverUserClient")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleJPEGDriverUserClient")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleH6CamInUserClient")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleH4CamInUserClient")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleH3CamInUserClient")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleH2CamInUserClient")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleMobileFileIntegrityUserClient")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-set-properties"),filters([])).
profileRule(profile("mediaserverd"),decision("allow"),operation("iokit-get-properties"),filters([])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name("shm_pcm_audio_sco_read")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name("shm_pcm_audio_sco_write")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^[0-9A-F][0-9A-F]:+[0-9A-F][0-9A-F]-tacl$"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^shm_notif[.][^.]+[.][RW]$"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^com[.]apple[.]audio[.]abl[.]"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^AppleAudioQueue[.]."/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^AppleAURemoteIO[.]."/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^AppleABL[.]."/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^AppleAudioQueue[.].+"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^AppleAURemoteIO[.].+"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^AppleABL[.].+"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name("shm_pcm_audio_acl")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^/FSM-"/i),debug-mode])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^OA-"/i),debug-mode])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^stack-logs"/i),debug-mode])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-c$"/i),debug-mode])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-s$"/i),debug-mode])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^/FSM-"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^OA-"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^stack-logs"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-c$"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-s$"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^/FSM-"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^OA-"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^stack-logs"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-c$"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-s$"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("mediaserverd"),decision("allow"),operation("ipc-posix-shm-readSTAR"),filters([ipc-posix-name("apple.shm.notification_center")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-bootstrap"),filters([])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.cfnetwork.AuthBrokerAgent")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.cfnetwork.cfnetworkagent")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.hangtracerd")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.ReportCrash.SimulateCrash")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.aggregated")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.xpcd")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.tccd")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.mobilegestalt.xpc")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.lsd")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.backboard.processassertionconnection")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.system.logger")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.system.notification_center")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.distributed_notifications@1v3")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.managedconfiguration.profiled.public")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.MediaRemote.daemon")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.MediaRemote.nowplayingserver")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.MediaRemote.isrunning")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.cvmsServ")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.gpumemd.source")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.audio.AURemoteIOServer")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.iTunesStore.daemon")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.iTunesStore.daemon.deatchwatch")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.iTunesStore.daemon-notifications")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.locationd.registration")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.locationd.synchronous")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.locationd.spi")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("PurpleSystemAppPort")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.wifi.manager")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.springboard.services")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.springboard.processinvalidation")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.springboard.backgroundappservices")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.server.bluetooth")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.securityd")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.securekeyvaultd")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.marco")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.lskdd")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.iohideventsystem")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.iap2d.xpc")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.iapd.xpc")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.iap2d.distributednotification.server")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.iapd.distributednotification.server")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.filesystems.userfsd")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.fairplayd.versioned")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coresymbolicationd")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.coremedia.virtualdisplayserver")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.commcenter.xpc")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.backboard.systemservices")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.backboard.display.services")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.backboard.applicationstateconnection")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.audio.SystemSounds")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.audio.AudioQueueServer")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.WirelessCoexManager")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SBUserNotification")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.PowerManagement.control")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.PersistentURLTranslator.Gatekeeper")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.NetworkLinkConditioner")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.CARenderServer")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("PurpleWorkspacePort")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.awdd")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.configd")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.NetworkInformation")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.PPPController")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.DNSConfiguration")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.SCNetworkReachability")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.commcenter.cupolicy.xpc")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.usymptomsd")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.symptomsd")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.networkd")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.nsnetworkd")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.itunesstored.xpc"),require-entitlement("com.apple.itunesstored.private",[])])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-register"),filters([global-name("com.apple.midiserver.io")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("mach-register"),filters([global-name-regex("^com[.]apple[.]coremedia[.]"/i)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("network-inbound"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),local(tcp("*:*"))])).
profileRule(profile("mediaserverd"),decision("allow"),operation("network-inbound"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),local(udp("*:*"))])).
profileRule(profile("mediaserverd"),decision("allow"),operation("network-outbound"),filters([control-name("com.apple.network.statistics")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("network-outbound"),filters([control-name("com.apple.netsrc")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("network-outbound"),filters([literal("/private/var/run/mDNSResponder")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("network-outbound"),filters([remote(udp("*:*"))])).
profileRule(profile("mediaserverd"),decision("allow"),operation("network-outbound"),filters([remote(tcp("*:*"))])).
profileRule(profile("mediaserverd"),decision("allow"),operation("network-outbound"),filters([literal("/private/var/run/lockdown.sock")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("network-outbound"),filters([literal("/private/var/run/syslog")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("network-outbound"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/tmp/launchd-[0-9]+[.][^/]+/sock$"/i))])).
profileRule(profile("mediaserverd"),decision("allow"),operation("privSTAR"),filters([])).
profileRule(profile("mediaserverd"),decision("allow"),operation("priv-adjtime"),filters([])).
profileRule(profile("mediaserverd"),decision("allow"),operation("priv-netinetSTAR"),filters([])).
profileRule(profile("mediaserverd"),decision("allow"),operation("priv-netinet-reservedport"),filters([])).
profileRule(profile("mediaserverd"),decision("allow"),operation("process-exec"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/usr/sbin/mediaserverd")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("process-exec"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),debug-mode,literal("/usr/bin/trace")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("process-exec"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),debug-mode,literal("/usr/bin/syslog")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("process-fork"),filters([debug-mode])).
profileRule(profile("mediaserverd"),decision("allow"),operation("process-infoSTAR"),filters([])).
profileRule(profile("mediaserverd"),decision("allow"),operation("process-info-listpids"),filters([])).
profileRule(profile("mediaserverd"),decision("allow"),operation("process-info-pidinfo"),filters([])).
profileRule(profile("mediaserverd"),decision("allow"),operation("process-info-pidfdinfo"),filters([])).
profileRule(profile("mediaserverd"),decision("allow"),operation("process-info-pidfileportinfo"),filters([])).
profileRule(profile("mediaserverd"),decision("allow"),operation("process-info-setcontrol"),filters([])).
profileRule(profile("mediaserverd"),decision("allow"),operation("process-info-dirtycontrol"),filters([])).
profileRule(profile("mediaserverd"),decision("allow"),operation("process-info-rusage"),filters([])).
profileRule(profile("mediaserverd"),decision("allow"),operation("pseudo-tty"),filters([])).
profileRule(profile("mediaserverd"),decision("allow"),operation("signal"),filters([target(self)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("sysctl-read"),filters([])).
profileRule(profile("mediaserverd"),decision("allow"),operation("system-info"),filters([info-type("net.link.addr")])).
profileRule(profile("mediaserverd"),decision("allow"),operation("system-sched"),filters([require-entitlement("com.apple.private.kernel.override-cpumon",[])])).
profileRule(profile("mediaserverd"),decision("allow"),operation("system-socket"),filters([socket-domain(af_route)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("system-socket"),filters([socket-domain(af_system),socket-protocol(2)])).
profileRule(profile("mediaserverd"),decision("allow"),operation("system-suspend-resume"),filters([])).
