

profileDefault(profile("MobileMaps"),decision("deny")).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/ptmx")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/dtracehelper")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/aes_0")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension-class("com.apple.quicklook.readonly")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension-class("com.apple.nsnetworkd.readonly")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension-class("com.apple.app-sandbox.read")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension-class("com.apple.app-sandbox.read-write")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension("com.apple.librarian.ubiquity-container"),subpath("/private/var/mobile/Library/Mobile Documents/"),extension-class("com.apple.app-sandbox.read")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.AppSupport.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.GEO.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.locationd.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/Managed Preferences/mobile/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.persistentconnection.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Caches/.com.apple.persistentconnection.settings.lock.lock")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Logs/PersistentConnection/com[.]apple[.]Maps"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Logs/CrashReporter/PersistentConnection/com[.]apple[.]Maps"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Caches/com.apple.persistentconnection.intervalcache.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Caches/com.apple.persistentconnection.intervalcache.plist.lock")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Media/com.apple.itunes.lock_sync")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.PeoplePicker.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.AOSNotification.public.notbackedup.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.accountsd.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.appleaccount.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Cookies$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Library/Cookies/Cookies[.]binarycookies"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.WebFoundation.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Applications/Maps.app/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/SystemConfiguration/com.apple.wifi.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Maps/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([regex("^/private/var/mobile/Applications/[-0-9A-Z]+/GeoJSON"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/Caches/Maps/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/SMS/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/com.apple.iTunesStore/LocalStorage/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.mms_override.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.weather.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.voiceservices.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.Maps.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.GMM.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.skyhookwireless.wps.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.assistant.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.assistant.backedup.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.internal.Voltaire.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/com.apple.networkd.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/com.apple.NetworkStatistics.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([subpath("/AppleInternal/Library/Bundles/MapsInternalExtras.bundle/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/tmp/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/db/timezone/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([subpath("/System/Library/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([subpath("/usr/lib/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([subpath("/usr/share/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/.GlobalPreferences.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([subpath("/System/Library/Frameworks/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([subpath("/System/Library/PrivateFrameworks/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Developer/"),debug-mode])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Developer/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Developer/"),require-not(require-entitlement("platform-application"))])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/tmp/"),debug-mode])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/tmp/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/XcodeBuiltProducts/"),debug-mode])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/XcodeBuiltProducts/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Caches/com.apple.itunesstored/url-resolution.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.SpeakSelection.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.voiceservices.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),subpath("/private/var/mobile/Library/VoiceServices/Assets/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),subpath("/private/var/mobile/Library/Assets/com_apple_MobileAsset_VoiceServicesVocalizerVoice/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.mediaaccessibility.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.mediaaccessibility.public.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.MobileAsset.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),subpath("/private/var/mobile/Library/Caches/com.apple.keyboards/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Keyboard/LocalDictionary")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.keyboard.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.InputModePreferences.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.assistant.support.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.Preferences.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),subpath("/private/var/mobile/Library/Fonts/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/preferences/SystemConfiguration/com.apple.accounts.exists.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/preferences/SystemConfiguration/com.apple.sinaweibo.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/preferences/SystemConfiguration/com.apple.linkedin.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/preferences/SystemConfiguration/com.apple.facebook.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/preferences/SystemConfiguration/com.apple.twitter.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),subpath("/private/var/mobile/Library/Caches/com.apple.IconsCache/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),subpath("/private/var/mobile/Library/Caches/com.apple.UIStatusBar/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.Sharing.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.CoreMotion.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.Accessibility.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.UIKit.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.WebUI.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.mt.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.preferences.sounds.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.telephonyutilities.dialassist.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/.GlobalPreferences.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.logging.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.MapKit.internal.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/preferences/SystemConfiguration/com.apple.radios.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/preferences/com.apple.networkd.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/preferences/com.apple.NetworkStatistics.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),subpath("/Library/Dictionaries/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),subpath("/private/var/mobile/Library/Dictionaries/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Caches/DateFormats.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),subpath("/private/var/mobile/Library/Caches/GeoServices/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.GEO.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Caches/Checkpoint.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Media/com.apple.itunes.lock_sync")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),subpath("/private/var/Managed Preferences/mobile/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.avfoundation.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.mobileslideshow.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.camera.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.springboard.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),subpath("/Library/Ringtones/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Media/Vibrations/UserGeneratedVibrationPatterns.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Maps[.]plist"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),regex("^/private/var/mobile/Library/SyncedPreferences/com[.]apple[.]Maps[.]plist"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),regex("^/private/var/mobile/Library/SyncedPreferences/com[.]apple[.]Maps-.+[.]plist"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),regex("^/private/var/mobile/Library/Caches/Snapshots/com[.]apple[.]Maps-"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),regex("^/private/var/mobile/Library/Caches/Snapshots/com[.]apple[.]Maps/"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),regex("^/private/var/mobile/Library/Caches/Snapshots/com[.]apple[.]Maps$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),regex("^/private/var/mobile/Documents/com[.]apple[.]Maps[.]settings$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),regex("^/private/var/mobile/Documents/com[.]apple[.]Maps[.]settings/"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),regex("^/private/var/mobile/Library/Saved Application State/com[.]apple[.]Maps.savedState/"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),regex("^/private/var/mobile/Library/Caches/com[.]apple[.]Maps/"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),regex("^/private/var/mobile/Library/Caches/com[.]apple[.]Maps$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.demo-settings.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.DataAccess.BehaviorOptions.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Cookies")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Cookies/com.apple.itunesstored.2.sqlitedb")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Cookies/com.apple.itunesstored.2.sqlitedb-journal")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.itunesstored.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.mobileipod.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Media/iTunes_Control/iTunes")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Media/iTunes_Control/iTunes/MediaLibrary.sqlitedb")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Media/iTunes_Control/iTunes/MediaLibrary.sqlitedb-journal")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Media/iTunes_Control/iTunes/MediaLibrary.sqlitedb-shm")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Media/iTunes_Control/iTunes/MediaLibrary.sqlitedb-wal")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Caches/com.apple.iTunesStore/network-constraints.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),regex("^/private/var/mobile/Library/Caches/com[.]apple[.]iTunesStore/ISURLBag/com[.]apple[.]Maps$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),regex("^/private/var/mobile/Library/Caches/com[.]apple[.]iTunesStore/ISURLBag/com[.]apple[.]Maps/$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),regex("^/private/var/mobile/Library/Caches/com[.]apple[.]iTunesStore/ISURLBag/com[.]apple[.]Maps/.+$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.coreaudio.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.coremedia.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.corevideo.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Library/Preferences/com.apple.homesharing.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),subpath("/private/var/mobile/Library/Mobile Documents/"),extension("com.apple.librarian.ubiquity-container")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),subpath("/private/var/mobile/Library/Application Support/Ubiquity/genstore/"),extension("com.apple.librarian.ubiquity-revision")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),subpath("/private/var/mobile/Library/Assets/"),extension("com.apple.assets.read")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),literal("/private/var/mobile/Library/Caches/com.apple.MobileGestalt.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),subpath("/private/var/mobile/Library/ConfigurationProfiles/PublicInfo/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),literal("/private/var/mobile/Library/Preferences/com.apple.carrier.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),regex("^/System/Library/Carrier Bundles//carrier[.]plist$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),regex("^/System/Library/Carrier Bundles/.+/carrier[.]plist$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),regex("^/private/var/mobile/Library/Carrier Bundles//carrier[.]plist$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),regex("^/private/var/mobile/Library/Carrier Bundles/.+/carrier[.]plist$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),regex("^/System/Library/Carrier Bundles/[.]png$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),regex("^/System/Library/Carrier Bundles/.+[.]png$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),regex("^/private/var/mobile/Library/Carrier Bundles/[.]png$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),regex("^/private/var/mobile/Library/Carrier Bundles/.+[.]png$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),subpath("/private/var/mobile/Library/Carrier Bundles/Overlay/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),regex("^/private/var/mobile/Library/Carrier Bundles/[.]bundle$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),regex("^/private/var/mobile/Library/Carrier Bundles/.+[.]bundle$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),regex("^/private/var/mobile/Library/Carrier Bundles/[.]bundle/Info[.]plist$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),regex("^/private/var/mobile/Library/Carrier Bundles/.+[.]bundle/Info[.]plist$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),regex("^/private/var/mobile/Library/Carrier Bundles/[.]bundle/[.]lproj/"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),regex("^/private/var/mobile/Library/Carrier Bundles/[.]bundle/[.]lproj$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),regex("^/private/var/mobile/Library/Carrier Bundles/.+[.]bundle/[.]lproj/"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),regex("^/private/var/mobile/Library/Carrier Bundles/.+[.]bundle/[.]lproj$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),regex("^/private/var/mobile/Library/Carrier Bundles/[.]bundle/[^/]+[.]lproj/"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),regex("^/private/var/mobile/Library/Carrier Bundles/[.]bundle/[^/]+[.]lproj$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),regex("^/private/var/mobile/Library/Carrier Bundles/.+[.]bundle/[^/]+[.]lproj/"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),regex("^/private/var/mobile/Library/Carrier Bundles/.+[.]bundle/[^/]+[.]lproj$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),literal("/dev/null")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),literal("/dev/zero")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),literal("/dev/random")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),literal("/dev/urandom")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),literal("/dev/aes_0")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),literal("/dev/ptmx")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),literal("/dev/dtracehelper")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),literal("/private/etc/hosts")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),literal("/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),literal("/private/etc/services")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),literal("/private/etc/protocols")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),literal("/private/etc/passwd")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),literal("/private/etc/group")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),vnode-type(tty),regex("^/dev/ttyp[0-9a-f]$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),vnode-type(tty),regex("^/dev/ptyp[0-9a-f]$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),regex("^/dev/ttys[0-9]"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(subpath("/private/var/mobile/Library/FairPlay/")),require-not(literal("/usr/sbin/fairplayd")),require-not(subpath("/private/var/mobile/Media/")),regex("^/dev/ttys[0-9]+"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),subpath("/private/var/mobile/Media/PhotoData/Metadata/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),subpath("/private/var/mobile/Media/PhotoData/Sync/FaceAlbumThumbnails/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),subpath("/private/var/mobile/Media/PhotoData/Thumbnails/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),literal("/private/var/mobile/Media/PhotoData/syncInfo.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),regex("^/private/var/mobile/Media/PhotoData/Photos.sqlite$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),regex("^/private/var/mobile/Media/PhotoData/Photos.sqlite-wal$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),regex("^/private/var/mobile/Media/PhotoData/Photos.sqlite-shm$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),regex("^/private/var/mobile/Media/PhotoData/Photos.sqlite-journal$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),extension("com.apple.tcc.kTCCServicePhotos")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/com.apple.mobilephone.speeddial.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/Library/AddressBook/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-readSTAR"),filters([extension("com.apple.tcc.kTCCServiceAddressBook")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-read-data"),filters([regex("^/private/var/ea/ea[.0-9]+$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-read-metadata"),filters([])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Library/Caches/.com.apple.persistentconnection.settings.lock.lock")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Library/Caches/com.apple.persistentconnection.intervalcache.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Library/Caches/com.apple.persistentconnection.intervalcache.plist.lock")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Media/com.apple.itunes.lock_sync")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Library/Maps/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Library/Caches/Maps/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Library/SMS/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Library/com.apple.iTunesStore/LocalStorage/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Maps[.]plist"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]GMM[.]plist"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]skyhookwireless[.]wps[.]plist"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]assistant[.]plist"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]assistant[.]backedup[.]plist"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]internal[.]Voltaire[.]plist"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Applications/[-0-9A-Z]+/GeoJSON"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Cookies$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Cookies/Cookies[.]binarycookies"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]PeoplePicker[.]plist"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Logs/PersistentConnection/com[.]apple[.]Maps"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/mobile/Library/Logs/CrashReporter/PersistentConnection/com[.]apple[.]Maps"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/"),debug-mode])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Library/Cookies")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Library/Cookies/com.apple.itunesstored.2.sqlitedb")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Media/iTunes_Control/iTunes/MediaLibrary.sqlitedb-journal")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]mobileipod[.]plist"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]itunesstored[.]plist"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Media/iTunes_Control/iTunes")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Media/iTunes_Control/iTunes/MediaLibrary.sqlitedb")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Media/iTunes_Control/iTunes/MediaLibrary.sqlitedb-shm")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Media/iTunes_Control/iTunes/MediaLibrary.sqlitedb-wal")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Library/Caches/com.apple.iTunesStore/network-constraints.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/com[.]apple[.]iTunesStore/ISURLBag/com[.]apple[.]Maps$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/com[.]apple[.]iTunesStore/ISURLBag/com[.]apple[.]Maps/$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/com[.]apple[.]iTunesStore/ISURLBag/com[.]apple[.]Maps/.+$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),subpath("/private/var/mobile/Library/Caches/com.apple.keyboards/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]mediaaccessibility[.]public[.]plist"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Library/Keyboard/LocalDictionary")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Preferences[.]plist"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Media/com.apple.itunes.lock_sync")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Maps[.]plist"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/Snapshots/com[.]apple[.]Maps-"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/Snapshots/com[.]apple[.]Maps/"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/Snapshots/com[.]apple[.]Maps$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Documents/com[.]apple[.]Maps[.]settings$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Documents/com[.]apple[.]Maps[.]settings/"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Saved Application State/com[.]apple[.]Maps.savedState/"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/com[.]apple[.]Maps/"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/com[.]apple[.]Maps$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Library/Cookies/com.apple.itunesstored.2.sqlitedb-journal")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),vnode-type(directory),literal("/private/var/mobile/Media/iTunes_Control/iTunes")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),subpath("/private/var/mobile/Library/Mobile Documents/"),extension("com.apple.librarian.ubiquity-container")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),require-not(subpath("/private/var/mobile/Media/")),literal("/dev/ptmx")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),require-not(subpath("/private/var/mobile/Media/")),literal("/dev/dtracehelper")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),require-not(subpath("/private/var/mobile/Media/")),literal("/dev/aes_0")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),require-not(subpath("/private/var/mobile/Media/")),vnode-type(tty),regex("^/dev/ttyp[0-9a-f]$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),require-not(subpath("/private/var/mobile/Media/")),vnode-type(tty),regex("^/dev/ptyp[0-9a-f]$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),require-not(subpath("/private/var/mobile/Media/")),regex("^/dev/ttys[0-9]"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),require-not(subpath("/private/var/mobile/Media/")),regex("^/dev/ttys[0-9]+"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),require-not(subpath("/private/var/mobile/Media/")),require-not(literal("/dev/urandom")),require-not(literal("/dev/random")),literal("/dev/zero")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/GeoServices/tguid.bin")),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),require-not(subpath("/private/var/mobile/Media/")),require-not(literal("/dev/urandom")),require-not(literal("/dev/random")),literal("/dev/null")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Library/Preferences/com.apple.mobilephone.speeddial.plist")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/mobile/Library/AddressBook/")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension("com.apple.tcc.kTCCServiceAddressBook")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(directory),literal("/private/var/mobile/Library/Logs/PersistentConnection")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(directory),literal("/private/var/mobile/Library/Logs/CrashReporter/PersistentConnection")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(directory),literal("/private/var/mobile/Library/Caches/com.apple.DictionaryServices")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),literal("/private/var/mobile/Library/Caches")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),literal("/private/var/mobile/Library/Saved Application State")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),regex("^/private/var/mobile/Library/Saved Application State/com[.]apple[.]Maps.savedState"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),literal("/private/var/mobile/Library/Caches/Snapshots")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),literal("/private/var/mobile/Library/com.apple.iTunesStore")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),literal("/private/var/mobile/Library/com.apple.iTunesStore/LocalStorage")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),literal("/private/var/mobile/Library/Caches/com.apple.iTunesStore")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),literal("/private/var/mobile/Library/Caches/com.apple.iTunesStore/ISURLBag")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(regular-file),extension("com.apple.private.safe-move.send")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Library/Cookies/com.apple.itunesstored.2.sqlitedb")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/mobile/Media/iTunes_Control/iTunes/MediaLibrary.sqlitedb")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/private/var/ea/ea[.0-9]+$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(regular-file),extension("com.apple.private.safe-move.send")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("file-write-unlink"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(regular-file),extension("com.apple.private.safe-move.receive")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelDevice2")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleMobileFileIntegrityUserClient")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleJPEGDriverUserClient")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOMobileFramebufferUserClient")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOSurfaceRootUserClient")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOSurfaceSendRight")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleM2ScalerCSCDriverUserClient")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleKeyStoreUserClient")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelSharedUserClient2")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelContext")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelDevice")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelSharedUserClient")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("IOAccelContext2")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("iokit-get-properties"),filters([])).
profileRule(profile("MobileMaps"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^/FSM-"/i),debug-mode])).
profileRule(profile("MobileMaps"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^OA-"/i),debug-mode])).
profileRule(profile("MobileMaps"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^stack-logs"/i),debug-mode])).
profileRule(profile("MobileMaps"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-c$"/i),debug-mode])).
profileRule(profile("MobileMaps"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-s$"/i),debug-mode])).
profileRule(profile("MobileMaps"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^/FSM-"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("MobileMaps"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^OA-"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("MobileMaps"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^stack-logs"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("MobileMaps"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-c$"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("MobileMaps"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-s$"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("MobileMaps"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^/FSM-"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("MobileMaps"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^OA-"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("MobileMaps"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^stack-logs"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("MobileMaps"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-c$"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("MobileMaps"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-s$"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("MobileMaps"),decision("allow"),operation("ipc-posix-shm-readSTAR"),filters([ipc-posix-name-regex("^Apple MIDI in [0-9]+$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("ipc-posix-shm-readSTAR"),filters([ipc-posix-name-regex("^Apple MIDI out [0-9]+$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("ipc-posix-shm-readSTAR"),filters([ipc-posix-name("apple.shm.notification_center")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("ipc-posix-shm-write-data"),filters([ipc-posix-name-regex("^Apple MIDI in [0-9]+$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("ipc-posix-shm-write-data"),filters([ipc-posix-name-regex("^Apple MIDI out [0-9]+$"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("ipc-posix-shm-write-data"),filters([ipc-posix-name("apple.shm.notification_center")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("mach-bootstrap"),filters([])).
profileRule(profile("MobileMaps"),decision("allow"),operation("mach-lookup"),filters([])).
profileRule(profile("MobileMaps"),decision("allow"),operation("mach-register"),filters([local-name("com.apple.iphone.axserver")])).
profileRule(profile("MobileMaps"),decision("allow"),operation("mach-register"),filters([global-name-regex("^com[.]apple[.]accessibility[.]gax[.]client-"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("mach-register"),filters([global-name-regex("^com[.]apple[.]assistant[.]contextprovider[.]"/i)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("network-outbound"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/tmp/launchd-[0-9]+[.][^/]+/sock$"/i))])).
profileRule(profile("MobileMaps"),decision("allow"),operation("privSTAR"),filters([])).
profileRule(profile("MobileMaps"),decision("allow"),operation("priv-adjtime"),filters([])).
profileRule(profile("MobileMaps"),decision("allow"),operation("priv-netinetSTAR"),filters([])).
profileRule(profile("MobileMaps"),decision("allow"),operation("priv-netinet-reservedport"),filters([])).
profileRule(profile("MobileMaps"),decision("allow"),operation("process-infoSTAR"),filters([])).
profileRule(profile("MobileMaps"),decision("allow"),operation("process-info-listpids"),filters([])).
profileRule(profile("MobileMaps"),decision("allow"),operation("process-info-pidinfo"),filters([])).
profileRule(profile("MobileMaps"),decision("allow"),operation("process-info-pidfdinfo"),filters([])).
profileRule(profile("MobileMaps"),decision("allow"),operation("process-info-pidfileportinfo"),filters([])).
profileRule(profile("MobileMaps"),decision("allow"),operation("process-info-setcontrol"),filters([])).
profileRule(profile("MobileMaps"),decision("allow"),operation("process-info-dirtycontrol"),filters([])).
profileRule(profile("MobileMaps"),decision("allow"),operation("process-info-rusage"),filters([])).
profileRule(profile("MobileMaps"),decision("allow"),operation("pseudo-tty"),filters([])).
profileRule(profile("MobileMaps"),decision("allow"),operation("signal"),filters([target(self)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("sysctl-read"),filters([])).
profileRule(profile("MobileMaps"),decision("allow"),operation("system-sched"),filters([require-entitlement("com.apple.private.kernel.override-cpumon",[])])).
profileRule(profile("MobileMaps"),decision("allow"),operation("system-socket"),filters([socket-domain(af_route)])).
profileRule(profile("MobileMaps"),decision("allow"),operation("system-socket"),filters([socket-domain(af_system),socket-protocol(2)])).
