

profileDefault(profile("racoon"),decision("deny")).
profileRule(profile("racoon"),decision("allow"),operation("fileSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/log/racoon.log")])).
profileRule(profile("racoon"),decision("allow"),operation("fileSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/Library/Keychains/System.keychain")])).
profileRule(profile("racoon"),decision("allow"),operation("fileSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/db/mds/system/mdsDirectory.db")])).
profileRule(profile("racoon"),decision("allow"),operation("fileSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/db/mds/system/mds.lock")])).
profileRule(profile("racoon"),decision("allow"),operation("fileSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/db/mds/system/mdsObject.db")])).
profileRule(profile("racoon"),decision("allow"),operation("fileSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/var/log/racoon.log")])).
profileRule(profile("racoon"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/etc/master.passwd/")])).
profileRule(profile("racoon"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/etc/racoon/")])).
profileRule(profile("racoon"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/preferences/SystemConfiguration/com.apple.ipsec.plist")])).
profileRule(profile("racoon"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/run/racoon/")])).
profileRule(profile("racoon"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/aes_0")])).
profileRule(profile("racoon"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/dtracehelper")])).
profileRule(profile("racoon"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/sha1_0")])).
profileRule(profile("racoon"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/dtracehelper")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/random")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/urandom")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/null")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/zero")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/dtracehelper")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/etc/master.passwd/")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/etc/racoon/")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/SystemConfiguration/com.apple.ipsec.plist")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/run/racoon/")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Library/Managed Preferences/")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/db/mds/messages/se_SecurityMessages")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/root/")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Library/Preferences/")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([subpath("/usr/share/")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/urandom")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/random")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/db/timezone/")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/null")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/zero")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/aes_0")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/dtracehelper")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([literal("/dev/sha1_0")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([file-mode("#o0004"),subpath("/usr/sbin/")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([file-mode("#o0004"),subpath("/usr/lib/")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([file-mode("#o0004"),subpath("/System/")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([file-mode("#o0004"),subpath("/usr/share/")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([file-mode("#o0004"),subpath("/usr/share/")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([file-mode("#o0004"),subpath("/usr/lib/")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([file-mode("#o0004"),subpath("/System/")])).
profileRule(profile("racoon"),decision("allow"),operation("file-readSTAR"),filters([file-mode("#o0004"),subpath("/private/var/db/dyld/")])).
profileRule(profile("racoon"),decision("allow"),operation("file-read-metadata"),filters([literal("/tmp")])).
profileRule(profile("racoon"),decision("allow"),operation("file-read-metadata"),filters([literal("/var")])).
profileRule(profile("racoon"),decision("allow"),operation("file-read-metadata"),filters([literal("/private/etc/localtime")])).
profileRule(profile("racoon"),decision("allow"),operation("file-read-metadata"),filters([literal("/etc")])).
profileRule(profile("racoon"),decision("allow"),operation("file-read-metadata"),filters([literal("/var")])).
profileRule(profile("racoon"),decision("allow"),operation("file-read-metadata"),filters([literal("/tmp")])).
profileRule(profile("racoon"),decision("allow"),operation("file-read-metadata"),filters([literal("/etc")])).
profileRule(profile("racoon"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/run/racoon.sock")])).
profileRule(profile("racoon"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/run/racoon.pid")])).
profileRule(profile("racoon"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),regex("^/cores/"/i),require-not(file-mode("#o0000"))])).
profileRule(profile("racoon"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/zero")])).
profileRule(profile("racoon"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/dtracehelper")])).
profileRule(profile("racoon"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/null")])).
profileRule(profile("racoon"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/zero")])).
profileRule(profile("racoon"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/aes_0")])).
profileRule(profile("racoon"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/dtracehelper")])).
profileRule(profile("racoon"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/sha1_0")])).
profileRule(profile("racoon"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/null")])).
profileRule(profile("racoon"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("AppleMobileFileIntegrityUserClient")])).
profileRule(profile("racoon"),decision("allow"),operation("iokit-open"),filters([iokit-user-client-class("RootDomainUserClient")])).
profileRule(profile("racoon"),decision("allow"),operation("iokit-get-properties"),filters([])).
profileRule(profile("racoon"),decision("allow"),operation("ipc-posixSTAR"),filters([ipc-posix-name("com.apple.securityd")])).
profileRule(profile("racoon"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name("com.apple.AppleDatabaseChanged")])).
profileRule(profile("racoon"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name("apple.shm.notification_center")])).
profileRule(profile("racoon"),decision("allow"),operation("mach-bootstrap"),filters([])).
profileRule(profile("racoon"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.system.logger")])).
profileRule(profile("racoon"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.system.notification_center")])).
profileRule(profile("racoon"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SecurityServer")])).
profileRule(profile("racoon"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.ocspd")])).
profileRule(profile("racoon"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.SystemConfiguration.configd")])).
profileRule(profile("racoon"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.securityd")])).
profileRule(profile("racoon"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.system.notification_center")])).
profileRule(profile("racoon"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.system.logger")])).
profileRule(profile("racoon"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.bsd.dirhelper")])).
profileRule(profile("racoon"),decision("allow"),operation("mach-lookup"),filters([global-name("com.apple.system.DirectoryService.libinfo_v1")])).
profileRule(profile("racoon"),decision("allow"),operation("networkSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),local(udp("*:500"))])).
profileRule(profile("racoon"),decision("allow"),operation("networkSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),remote(udp("*:*"))])).
profileRule(profile("racoon"),decision("allow"),operation("networkSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/private/var/run/racoon.sock")])).
profileRule(profile("racoon"),decision("allow"),operation("networkSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),local(udp("*:4500"))])).
profileRule(profile("racoon"),decision("allow"),operation("network-outbound"),filters([subpath("/private/var/tmp/launchd/")])).
profileRule(profile("racoon"),decision("allow"),operation("network-outbound"),filters([literal("/private/var/run/asl_input")])).
profileRule(profile("racoon"),decision("allow"),operation("network-outbound"),filters([literal("/private/var/run/syslog")])).
profileRule(profile("racoon"),decision("allow"),operation("network-outbound"),filters([control-name("com.apple.net.ipsec_control")])).
profileRule(profile("racoon"),decision("allow"),operation("network-outbound"),filters([literal("/private/var/run/asl_input")])).
profileRule(profile("racoon"),decision("allow"),operation("network-outbound"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/tmp/launchd-[0-9]+[.][^/]+/sock$"/i))])).
profileRule(profile("racoon"),decision("allow"),operation("privSTAR"),filters([])).
profileRule(profile("racoon"),decision("allow"),operation("priv-adjtime"),filters([])).
profileRule(profile("racoon"),decision("allow"),operation("priv-netinetSTAR"),filters([])).
profileRule(profile("racoon"),decision("allow"),operation("priv-netinet-reservedport"),filters([])).
profileRule(profile("racoon"),decision("allow"),operation("process-infoSTAR"),filters([])).
profileRule(profile("racoon"),decision("allow"),operation("process-info-listpids"),filters([])).
profileRule(profile("racoon"),decision("allow"),operation("process-info-pidinfo"),filters([])).
profileRule(profile("racoon"),decision("allow"),operation("process-info-pidfdinfo"),filters([])).
profileRule(profile("racoon"),decision("allow"),operation("process-info-pidfileportinfo"),filters([])).
profileRule(profile("racoon"),decision("allow"),operation("process-info-setcontrol"),filters([])).
profileRule(profile("racoon"),decision("allow"),operation("process-info-dirtycontrol"),filters([])).
profileRule(profile("racoon"),decision("allow"),operation("process-info-rusage"),filters([])).
profileRule(profile("racoon"),decision("allow"),operation("signal"),filters([target(self)])).
profileRule(profile("racoon"),decision("allow"),operation("signal"),filters([target(self)])).
profileRule(profile("racoon"),decision("allow"),operation("sysctlSTAR"),filters([])).
profileRule(profile("racoon"),decision("allow"),operation("sysctl-read"),filters([])).
profileRule(profile("racoon"),decision("allow"),operation("sysctl-write"),filters([])).
profileRule(profile("racoon"),decision("allow"),operation("system-info"),filters([info-type("net.link.addr")])).
profileRule(profile("racoon"),decision("allow"),operation("system-socket"),filters([])).
