

profileDefault(profile("Stocks"),decision("deny")).
profileRule(profile("Stocks"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/ptmx")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/dtracehelper")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-ioctl"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),literal("/dev/aes_0")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension-class("com.apple.app-sandbox.read-write")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension-class("com.apple.quicklook.readonly")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension-class("com.apple.nsnetworkd.readonly")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension-class("com.apple.app-sandbox.read")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-issue-extension"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),extension("com.apple.librarian.ubiquity-container"),subpath("/private/var/mobile/Library/Mobile Documents/"),extension-class("com.apple.app-sandbox.read")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/com.apple.networkd.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/preferences/com.apple.NetworkStatistics.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/tmp/")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/db/timezone/")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([subpath("/System/Library/")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([subpath("/usr/lib/")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([subpath("/usr/share/")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/Managed Preferences/mobile/")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([literal("/private/var/mobile/Library/Preferences/.GlobalPreferences.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([subpath("/System/Library/Frameworks/")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([subpath("/System/Library/PrivateFrameworks/")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Developer/"),debug-mode])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Developer/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([subpath("/Developer/"),require-not(require-entitlement("platform-application"))])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/tmp/"),debug-mode])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/tmp/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/XcodeBuiltProducts/"),debug-mode])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([subpath("/private/var/mobile/XcodeBuiltProducts/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/dev/zero")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/dev/random")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/dev/urandom")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/dev/aes_0")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/dev/ptmx")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/dev/dtracehelper")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.carrier.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/System/Library/Carrier Bundles//carrier[.]plist$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/System/Library/Carrier Bundles/.+/carrier[.]plist$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Carrier Bundles//carrier[.]plist$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Carrier Bundles/.+/carrier[.]plist$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/System/Library/Carrier Bundles/[.]png$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/System/Library/Carrier Bundles/.+[.]png$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Carrier Bundles/[.]png$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Carrier Bundles/.+[.]png$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),subpath("/private/var/mobile/Library/Carrier Bundles/Overlay/")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),subpath("/private/var/Managed Preferences/mobile/")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Cookies$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Cookies/Cookies[.]binarycookies"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Carrier Bundles/[.]bundle$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Carrier Bundles/.+[.]bundle$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Carrier Bundles/[.]bundle/Info[.]plist$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Carrier Bundles/.+[.]bundle/Info[.]plist$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Carrier Bundles/[.]bundle/[.]lproj/"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Carrier Bundles/[.]bundle/[.]lproj$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Carrier Bundles/.+[.]bundle/[.]lproj/"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Carrier Bundles/.+[.]bundle/[.]lproj$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Carrier Bundles/[.]bundle/[^/]+[.]lproj/"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Carrier Bundles/[.]bundle/[^/]+[.]lproj$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Carrier Bundles/.+[.]bundle/[^/]+[.]lproj/"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Carrier Bundles/.+[.]bundle/[^/]+[.]lproj$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.WebFoundation.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Stocks$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Stocks/"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.stocks.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Caches/com.apple.pep.configuration.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.ConfigServer.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Cookies$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Cookies/Cookies[.]binarycookies"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/preferences/com.apple.networkd.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/preferences/com.apple.NetworkStatistics.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]stocks[.]plist"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/SyncedPreferences/com[.]apple[.]stocks[.]plist"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/SyncedPreferences/com[.]apple[.]stocks-.+[.]plist"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Caches/Snapshots/com[.]apple[.]stocks-"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Caches/Snapshots/com[.]apple[.]stocks/"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Caches/Snapshots/com[.]apple[.]stocks$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Documents/com[.]apple[.]stocks[.]settings$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Documents/com[.]apple[.]stocks[.]settings/"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Saved Application State/com[.]apple[.]stocks.savedState/"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Caches/com[.]apple[.]stocks/"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/private/var/mobile/Library/Caches/com[.]apple[.]stocks$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.demo-settings.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.DataAccess.BehaviorOptions.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.avfoundation.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.coreaudio.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.coremedia.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.corevideo.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.homesharing.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.itunesstored.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Caches/com.apple.itunesstored/url-resolution.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.SpeakSelection.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.voiceservices.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),subpath("/private/var/mobile/Library/VoiceServices/Assets/")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),subpath("/private/var/mobile/Library/Assets/com_apple_MobileAsset_VoiceServicesVocalizerVoice/")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.mediaaccessibility.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.mediaaccessibility.public.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.MobileAsset.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),subpath("/private/var/mobile/Library/Caches/com.apple.keyboards/")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Keyboard/LocalDictionary")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.keyboard.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.InputModePreferences.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.assistant.support.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.Preferences.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),subpath("/private/var/mobile/Library/Fonts/")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/preferences/SystemConfiguration/com.apple.accounts.exists.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/preferences/SystemConfiguration/com.apple.sinaweibo.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/preferences/SystemConfiguration/com.apple.linkedin.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/preferences/SystemConfiguration/com.apple.facebook.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/preferences/SystemConfiguration/com.apple.twitter.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),subpath("/private/var/mobile/Library/Caches/com.apple.IconsCache/")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),subpath("/private/var/mobile/Library/Caches/com.apple.UIStatusBar/")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.Sharing.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.CoreMotion.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.Accessibility.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.UIKit.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.WebUI.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.mt.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.preferences.sounds.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.telephonyutilities.dialassist.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/.GlobalPreferences.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.logging.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.MapKit.internal.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/preferences/SystemConfiguration/com.apple.radios.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),subpath("/Library/Dictionaries/")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),subpath("/private/var/mobile/Library/Dictionaries/")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Caches/DateFormats.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.AppSupport.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.GEO.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/private/var/mobile/Library/Preferences/com.apple.locationd.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),literal("/dev/null")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),vnode-type(tty),regex("^/dev/ttyp[0-9a-f]$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),vnode-type(tty),regex("^/dev/ptyp[0-9a-f]$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/dev/ttys[0-9]"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),regex("^/dev/ttys[0-9]+"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),subpath("/private/var/mobile/Library/Mobile Documents/"),extension("com.apple.librarian.ubiquity-container")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),subpath("/private/var/mobile/Library/Application Support/Ubiquity/genstore/"),extension("com.apple.librarian.ubiquity-revision")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),subpath("/private/var/mobile/Library/Assets/"),extension("com.apple.assets.read")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(subpath("/dev/")),literal("/private/etc/group")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(subpath("/dev/")),literal("/private/etc/passwd")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(subpath("/dev/")),literal("/private/etc/protocols")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(subpath("/dev/")),literal("/private/etc/services")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(subpath("/dev/")),literal("/")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(subpath("/dev/")),literal("/private/var/mobile/Library/Caches/com.apple.MobileGestalt.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(subpath("/dev/")),subpath("/private/var/mobile/Library/ConfigurationProfiles/PublicInfo/")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(subpath("/dev/")),literal("/private/etc/hosts")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-readSTAR"),filters([require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(subpath("/dev/")),require-not(regex("^/private/var/mobile/Library/"/i))])).
profileRule(profile("Stocks"),decision("allow"),operation("file-read-metadata"),filters([literal("/private/var/mobile/Library/Caches/com.apple.DictionaryServices")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-read-metadata"),filters([vnode-type(symlink)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-read-metadata"),filters([vnode-type(directory)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-read-metadata"),filters([literal("/private/var/mobile/Library/Caches/powerlog.launchd")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-read-metadata"),filters([literal("/private/var/run/syslog")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-read-metadata"),filters([subpath("/private/var/mobile/Library/Carrier Bundles/")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-read-metadata"),filters([literal("/private/var/mobile")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-read-metadata"),filters([literal("/private/var/mobile/Library/Preferences")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-read-metadata"),filters([literal("/private/var/mobile/Library/Caches")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-read-metadata"),filters([literal("/private/var/mobile/Library/Saved Application State")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-read-metadata"),filters([literal("/private/var/mobile/Library/Caches/Snapshots")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-read-metadata"),filters([regex("^/private/var/mobile/Library/Saved Application State/com[.]apple[.]stocks.savedState"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-read-metadata"),filters([literal("/private/var/mobile/Library")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-read-metadata"),filters([literal("/private/var/mobile/Library/Mobile Documents")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-read-metadata"),filters([literal("/private/var/mobile/Library/PPTDevice")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-read-metadata"),filters([vnode-type(directory),literal("/private/var/mobile/Library/Caches/com.apple.DictionaryServices")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-read-metadata"),filters([vnode-type(regular-file),extension("com.apple.private.safe-move.send")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-read-metadata"),filters([vnode-type(regular-file),extension("com.apple.private.safe-move.receive")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-read-metadata"),filters([vnode-type(directory),literal("/private/var/mobile/Library/Caches")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-read-metadata"),filters([vnode-type(directory),literal("/private/var/mobile/Library/Saved Application State")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-read-metadata"),filters([vnode-type(directory),regex("^/private/var/mobile/Library/Saved Application State/com[.]apple[.]stocks.savedState"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-read-metadata"),filters([vnode-type(directory),literal("/private/var/mobile/Library/Caches/Snapshots")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/"),debug-mode])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),subpath("/private/var/tmp/"),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),subpath("/private/var/mobile/Library/Caches/com.apple.keyboards/")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]mediaaccessibility[.]public[.]plist"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]stocks[.]plist"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/Snapshots/com[.]apple[.]stocks-"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/Snapshots/com[.]apple[.]stocks/"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/Snapshots/com[.]apple[.]stocks$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Documents/com[.]apple[.]stocks[.]settings$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Documents/com[.]apple[.]stocks[.]settings/"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Saved Application State/com[.]apple[.]stocks.savedState/"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/com[.]apple[.]stocks/"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Caches/com[.]apple[.]stocks$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Library/Keyboard/LocalDictionary")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Preferences[.]plist"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/dev/aes_0")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/dev/ptmx")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/dev/dtracehelper")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),literal("/private/var/mobile/Library/Caches/com.apple.pep.configuration.plist")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]stocks[.]plist"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Stocks$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Stocks/"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Cookies$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/private/var/mobile/Library/Cookies/Cookies[.]binarycookies"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),vnode-type(tty),regex("^/dev/ttyp[0-9a-f]$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),vnode-type(tty),regex("^/dev/ptyp[0-9a-f]$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/dev/ttys[0-9]"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),regex("^/dev/ttys[0-9]+"/i),extension("com.apple.sandbox.pty")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),subpath("/private/var/mobile/Library/Mobile Documents/"),extension("com.apple.librarian.ubiquity-container")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),require-not(literal("/dev/urandom")),require-not(literal("/dev/random")),literal("/dev/zero")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-writeSTAR"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Applications/$"/i)),require-not(regex("^/private/var/mobile/Applications/.+$"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]springboard[.]plist"/i)),require-not(literal("/private/var/mobile/Library/Caches/DateFormats.plist")),require-not(literal("/dev/urandom")),require-not(literal("/dev/random")),literal("/dev/null")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(directory),literal("/private/var/mobile/Library/Caches/com.apple.DictionaryServices")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),literal("/private/var/mobile/Library/Caches")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),literal("/private/var/mobile/Library/Saved Application State")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),regex("^/private/var/mobile/Library/Saved Application State/com[.]apple[.]stocks.savedState"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(directory),literal("/private/var/mobile/Library/Caches/Snapshots")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-write-create"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]Accessibility[.]plist"/i)),require-not(regex("^/private/var/mobile/Library/Preferences/com[.]apple[.]UIKit[.]plist"/i)),vnode-type(regular-file),extension("com.apple.private.safe-move.send")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-write-data"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(regular-file),extension("com.apple.private.safe-move.send")])).
profileRule(profile("Stocks"),decision("allow"),operation("file-write-unlink"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),vnode-type(regular-file),extension("com.apple.private.safe-move.receive")])).
profileRule(profile("Stocks"),decision("allow"),operation("iokit-open"),filters([])).
profileRule(profile("Stocks"),decision("allow"),operation("iokit-set-properties"),filters([])).
profileRule(profile("Stocks"),decision("allow"),operation("iokit-get-properties"),filters([])).
profileRule(profile("Stocks"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^/FSM-"/i),debug-mode])).
profileRule(profile("Stocks"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^OA-"/i),debug-mode])).
profileRule(profile("Stocks"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^stack-logs"/i),debug-mode])).
profileRule(profile("Stocks"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-c$"/i),debug-mode])).
profileRule(profile("Stocks"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-s$"/i),debug-mode])).
profileRule(profile("Stocks"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^/FSM-"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("Stocks"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^OA-"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("Stocks"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^stack-logs"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("Stocks"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-c$"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("Stocks"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-s$"/i),require-entitlement("com.apple.private.security.sandbox.debug-mode",[])])).
profileRule(profile("Stocks"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^/FSM-"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("Stocks"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^OA-"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("Stocks"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^stack-logs"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("Stocks"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-c$"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("Stocks"),decision("allow"),operation("ipc-posix-shmSTAR"),filters([ipc-posix-name-regex("^gdt-[0-9A-Za-z]+-s$"/i),require-not(require-entitlement("platform-application"))])).
profileRule(profile("Stocks"),decision("allow"),operation("ipc-posix-shm-readSTAR"),filters([ipc-posix-name-regex("^Apple MIDI in [0-9]+$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("ipc-posix-shm-readSTAR"),filters([ipc-posix-name-regex("^Apple MIDI out [0-9]+$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("ipc-posix-shm-readSTAR"),filters([ipc-posix-name("apple.shm.notification_center")])).
profileRule(profile("Stocks"),decision("allow"),operation("ipc-posix-shm-write-data"),filters([ipc-posix-name-regex("^Apple MIDI in [0-9]+$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("ipc-posix-shm-write-data"),filters([ipc-posix-name-regex("^Apple MIDI out [0-9]+$"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("ipc-posix-shm-write-data"),filters([ipc-posix-name("apple.shm.notification_center")])).
profileRule(profile("Stocks"),decision("allow"),operation("mach-bootstrap"),filters([])).
profileRule(profile("Stocks"),decision("allow"),operation("mach-lookup"),filters([])).
profileRule(profile("Stocks"),decision("allow"),operation("mach-register"),filters([local-name("com.apple.iphone.axserver")])).
profileRule(profile("Stocks"),decision("allow"),operation("mach-register"),filters([global-name-regex("^com[.]apple[.]accessibility[.]gax[.]client-"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("mach-register"),filters([global-name-regex("^com[.]apple[.]assistant[.]contextprovider[.]"/i)])).
profileRule(profile("Stocks"),decision("allow"),operation("network-outbound"),filters([require-not(subpath("/private/var/tmp/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.sandbox/")),require-not(regex("^/private/tmp/launchd-[0-9]+[.][^/]+/sock$"/i))])).
profileRule(profile("Stocks"),decision("allow"),operation("privSTAR"),filters([])).
profileRule(profile("Stocks"),decision("allow"),operation("priv-adjtime"),filters([])).
profileRule(profile("Stocks"),decision("allow"),operation("priv-netinetSTAR"),filters([])).
profileRule(profile("Stocks"),decision("allow"),operation("priv-netinet-reservedport"),filters([])).
profileRule(profile("Stocks"),decision("allow"),operation("process-infoSTAR"),filters([])).
profileRule(profile("Stocks"),decision("allow"),operation("process-info-listpids"),filters([])).
profileRule(profile("Stocks"),decision("allow"),operation("process-info-pidinfo"),filters([])).
profileRule(profile("Stocks"),decision("allow"),operation("process-info-pidfdinfo"),filters([])).
profileRule(profile("Stocks"),decision("allow"),operation("process-info-pidfileportinfo"),filters([])).
profileRule(profile("Stocks"),decision("allow"),operation("process-info-setcontrol"),filters([])).
profileRule(profile("Stocks"),decision("allow"),operation("process-info-dirtycontrol"),filters([])).
profileRule(profile("Stocks"),decision("allow"),operation("process-info-rusage"),filters([])).
profileRule(profile("Stocks"),decision("allow"),operation("pseudo-tty"),filters([])).
profileRule(profile("Stocks"),decision("allow"),operation("signal"),filters([target(self)])).
profileRule(profile("Stocks"),decision("allow"),operation("sysctl-read"),filters([])).
profileRule(profile("Stocks"),decision("allow"),operation("system-sched"),filters([require-entitlement("com.apple.private.kernel.override-cpumon",[])])).
profileRule(profile("Stocks"),decision("allow"),operation("system-socket"),filters([socket-domain(af_route)])).
profileRule(profile("Stocks"),decision("allow"),operation("system-socket"),filters([socket-domain(af_system),socket-protocol(2)])).
